const WORDS_EASY = [
{"es":"agua","en":"water","pos":"n","emoji":"💧","ctx":"Necesito un vaso de agua."},
{"es":"pan","en":"bread","pos":"n","emoji":"🍞","ctx":"Compro pan todos los días."},
{"es":"leche","en":"milk","pos":"n","emoji":"🥛","ctx":"Me gusta la leche fría."},
{"es":"café","en":"coffee","pos":"n","emoji":"☕","ctx":"Tomo café por la mañana."},
{"es":"arroz","en":"rice","pos":"n","emoji":"🍚","ctx":"El arroz está listo."},
{"es":"carne","en":"meat","pos":"n","emoji":"🥩","ctx":"La carne está muy buena."},
{"es":"pollo","en":"chicken","pos":"n","emoji":"🍗","ctx":"Voy a cocinar pollo hoy."},
{"es":"pescado","en":"fish","pos":"n","emoji":"🐟","ctx":"El pescado es muy fresco."},
{"es":"fruta","en":"fruit","pos":"n","emoji":"🍎","ctx":"La fruta es saludable."},
{"es":"manzana","en":"apple","pos":"n","emoji":"🍏","ctx":"Quiero una manzana roja."},
{"es":"naranja","en":"orange","pos":"n","emoji":"🍊","ctx":"La naranja tiene mucha vitamina."},
{"es":"plátano","en":"banana","pos":"n","emoji":"🍌","ctx":"El plátano está maduro."},
{"es":"uva","en":"grape","pos":"n","emoji":"🍇","ctx":"Las uvas son dulces."},
{"es":"fresa","en":"strawberry","pos":"n","emoji":"🍓","ctx":"Me encantan las fresas."},
{"es":"tomate","en":"tomato","pos":"n","emoji":"🍅","ctx":"Necesito un tomate para la ensalada."},
{"es":"queso","en":"cheese","pos":"n","emoji":"🧀","ctx":"El queso está delicioso."},
{"es":"huevo","en":"egg","pos":"n","emoji":"🥚","ctx":"Quiero dos huevos fritos."},
{"es":"sal","en":"salt","pos":"n","emoji":"🧂","ctx":"La sopa necesita más sal."},
{"es":"azúcar","en":"sugar","pos":"n","emoji":"🍬","ctx":"No pongo azúcar en el café."},
{"es":"aceite","en":"oil","pos":"n","emoji":"🫒","ctx":"Usa aceite de oliva."},
{"es":"vino","en":"wine","pos":"n","emoji":"🍷","ctx":"Un vaso de vino tinto, por favor."},
{"es":"cerveza","en":"beer","pos":"n","emoji":"🍺","ctx":"¿Quieres una cerveza?"},
{"es":"jugo","en":"juice","pos":"n","emoji":"🧃","ctx":"El jugo de naranja es rico."},
{"es":"sopa","en":"soup","pos":"n","emoji":"🍲","ctx":"La sopa está caliente."},
{"es":"ensalada","en":"salad","pos":"n","emoji":"🥗","ctx":"Quiero una ensalada grande."},
{"es":"postre","en":"dessert","pos":"n","emoji":"🍰","ctx":"¿Qué hay de postre?"},
{"es":"helado","en":"ice cream","pos":"n","emoji":"🍦","ctx":"El helado de chocolate es mi favorito."},
{"es":"galleta","en":"cookie","pos":"n","emoji":"🍪","ctx":"Las galletas están crujientes."},
{"es":"pastel","en":"cake","pos":"n","emoji":"🎂","ctx":"El pastel de cumpleaños es grande."},
{"es":"chocolate","en":"chocolate","pos":"n","emoji":"🍫","ctx":"Me encanta el chocolate."},
{"es":"mantequilla","en":"butter","pos":"n","emoji":"🧈","ctx":"Pon mantequilla en el pan."},
{"es":"harina","en":"flour","pos":"n","emoji":"🌾","ctx":"Necesito harina para el pastel."},
{"es":"pimienta","en":"pepper","pos":"n","emoji":"🌶️","ctx":"Agrega un poco de pimienta."},
{"es":"cebolla","en":"onion","pos":"n","emoji":"🧅","ctx":"Corta la cebolla en pedazos."},
{"es":"ajo","en":"garlic","pos":"n","emoji":"🧄","ctx":"El ajo le da sabor a la comida."},
{"es":"lechuga","en":"lettuce","pos":"n","emoji":"🥬","ctx":"La lechuga está muy fresca."},
{"es":"zanahoria","en":"carrot","pos":"n","emoji":"🥕","ctx":"Las zanahorias son buenas para la vista."},
{"es":"papa","en":"potato","pos":"n","emoji":"🥔","ctx":"Las papas fritas son ricas."},
{"es":"limón","en":"lemon","pos":"n","emoji":"🍋","ctx":"Quiero agua con limón."},
{"es":"sandía","en":"watermelon","pos":"n","emoji":"🍉","ctx":"La sandía es perfecta en verano."},
{"es":"comida","en":"food","pos":"n","emoji":"🍽️","ctx":"La comida mexicana es deliciosa."},
{"es":"desayuno","en":"breakfast","pos":"n","emoji":"🌅","ctx":"El desayuno es a las ocho."},
{"es":"almuerzo","en":"lunch","pos":"n","emoji":"🥪","ctx":"¿Qué quieres para el almuerzo?"},
{"es":"cena","en":"dinner","pos":"n","emoji":"🌙","ctx":"La cena está lista."},
{"es":"bebida","en":"drink","pos":"n","emoji":"🥤","ctx":"¿Qué bebida prefieres?"},
{"es":"receta","en":"recipe","pos":"n","emoji":"📋","ctx":"Tengo una receta nueva."},
{"es":"cerdo","en":"pork","pos":"n","emoji":"🐷","ctx":"La carne de cerdo está bien cocida."},
{"es":"jamón","en":"ham","pos":"n","emoji":"🥓","ctx":"Un sándwich de jamón y queso."},
{"es":"maíz","en":"corn","pos":"n","emoji":"🌽","ctx":"El maíz es amarillo."},
{"es":"pera","en":"pear","pos":"n","emoji":"🍐","ctx":"La pera está muy jugosa."},
{"es":"piña","en":"pineapple","pos":"n","emoji":"🍍","ctx":"La piña es tropical."},
{"es":"durazno","en":"peach","pos":"n","emoji":"🍑","ctx":"El durazno está maduro."},
{"es":"nuez","en":"nut","pos":"n","emoji":"🥜","ctx":"Las nueces son nutritivas."},
{"es":"miel","en":"honey","pos":"n","emoji":"🍯","ctx":"La miel es muy dulce."},
{"es":"salsa","en":"sauce","pos":"n","emoji":"🫙","ctx":"La salsa picante es deliciosa."},
{"es":"hamburguesa","en":"hamburger","pos":"n","emoji":"🍔","ctx":"Quiero una hamburguesa con queso."},
{"es":"pizza","en":"pizza","pos":"n","emoji":"🍕","ctx":"Pedimos una pizza grande."},
{"es":"té","en":"tea","pos":"n","emoji":"🍵","ctx":"¿Quieres una taza de té?"},
{"es":"perro","en":"dog","pos":"n","emoji":"🐕","ctx":"Mi perro es muy grande."},
{"es":"gato","en":"cat","pos":"n","emoji":"🐈","ctx":"El gato duerme en el sofá."},
{"es":"pájaro","en":"bird","pos":"n","emoji":"🐦","ctx":"El pájaro canta en el árbol."},
{"es":"pez","en":"fish","pos":"n","emoji":"🐠","ctx":"Tengo un pez en la pecera."},
{"es":"caballo","en":"horse","pos":"n","emoji":"🐴","ctx":"El caballo corre rápido."},
{"es":"vaca","en":"cow","pos":"n","emoji":"🐄","ctx":"La vaca da leche."},
{"es":"oveja","en":"sheep","pos":"n","emoji":"🐑","ctx":"Las ovejas están en el campo."},
{"es":"gallina","en":"hen","pos":"n","emoji":"🐔","ctx":"La gallina pone huevos."},
{"es":"ratón","en":"mouse","pos":"n","emoji":"🐭","ctx":"El ratón es muy pequeño."},
{"es":"conejo","en":"rabbit","pos":"n","emoji":"🐰","ctx":"El conejo salta mucho."},
{"es":"oso","en":"bear","pos":"n","emoji":"🐻","ctx":"El oso vive en el bosque."},
{"es":"león","en":"lion","pos":"n","emoji":"🦁","ctx":"El león es el rey de la selva."},
{"es":"tigre","en":"tiger","pos":"n","emoji":"🐯","ctx":"El tigre tiene rayas negras."},
{"es":"elefante","en":"elephant","pos":"n","emoji":"🐘","ctx":"El elefante es muy grande."},
{"es":"mono","en":"monkey","pos":"n","emoji":"🐒","ctx":"El mono come plátanos."},
{"es":"serpiente","en":"snake","pos":"n","emoji":"🐍","ctx":"La serpiente es larga."},
{"es":"tortuga","en":"turtle","pos":"n","emoji":"🐢","ctx":"La tortuga camina lento."},
{"es":"mariposa","en":"butterfly","pos":"n","emoji":"🦋","ctx":"La mariposa es muy bonita."},
{"es":"abeja","en":"bee","pos":"n","emoji":"🐝","ctx":"La abeja hace miel."},
{"es":"hormiga","en":"ant","pos":"n","emoji":"🐜","ctx":"Las hormigas son muy trabajadoras."},
{"es":"mosca","en":"fly","pos":"n","emoji":"🪰","ctx":"Hay una mosca en la cocina."},
{"es":"araña","en":"spider","pos":"n","emoji":"🕷️","ctx":"La araña tiene ocho patas."},
{"es":"lobo","en":"wolf","pos":"n","emoji":"🐺","ctx":"El lobo vive en el bosque."},
{"es":"zorro","en":"fox","pos":"n","emoji":"🦊","ctx":"El zorro es muy listo."},
{"es":"pato","en":"duck","pos":"n","emoji":"🦆","ctx":"El pato nada en el lago."},
{"es":"ballena","en":"whale","pos":"n","emoji":"🐋","ctx":"La ballena es el animal más grande."},
{"es":"delfín","en":"dolphin","pos":"n","emoji":"🐬","ctx":"El delfín es muy inteligente."},
{"es":"tiburón","en":"shark","pos":"n","emoji":"🦈","ctx":"El tiburón vive en el mar."},
{"es":"pulpo","en":"octopus","pos":"n","emoji":"🐙","ctx":"El pulpo tiene ocho brazos."},
{"es":"rana","en":"frog","pos":"n","emoji":"🐸","ctx":"La rana salta en el agua."},
{"es":"loro","en":"parrot","pos":"n","emoji":"🦜","ctx":"El loro puede hablar."},
{"es":"águila","en":"eagle","pos":"n","emoji":"🦅","ctx":"El águila vuela muy alto."},
{"es":"ciervo","en":"deer","pos":"n","emoji":"🦌","ctx":"El ciervo vive en el bosque."},
{"es":"jirafa","en":"giraffe","pos":"n","emoji":"🦒","ctx":"La jirafa tiene un cuello largo."},
{"es":"cebra","en":"zebra","pos":"n","emoji":"🦓","ctx":"La cebra tiene rayas blancas y negras."},
{"es":"pingüino","en":"penguin","pos":"n","emoji":"🐧","ctx":"El pingüino vive en el hielo."},
{"es":"búho","en":"owl","pos":"n","emoji":"🦉","ctx":"El búho sale por la noche."},
{"es":"caracol","en":"snail","pos":"n","emoji":"🐌","ctx":"El caracol camina muy lento."},
{"es":"cangrejo","en":"crab","pos":"n","emoji":"🦀","ctx":"El cangrejo camina de lado."},
{"es":"burro","en":"donkey","pos":"n","emoji":"🫏","ctx":"El burro carga las cosas."},
{"es":"cocodrilo","en":"crocodile","pos":"n","emoji":"🐊","ctx":"El cocodrilo vive en el río."},
{"es":"gorila","en":"gorilla","pos":"n","emoji":"🦍","ctx":"El gorila es muy fuerte."},
{"es":"toro","en":"bull","pos":"n","emoji":"🐂","ctx":"El toro es muy grande."},
{"es":"gusano","en":"worm","pos":"n","emoji":"🪱","ctx":"El gusano vive en la tierra."},
{"es":"mascota","en":"pet","pos":"n","emoji":"🐾","ctx":"Mi mascota es un perro."},
{"es":"animal","en":"animal","pos":"n","emoji":"🐾","ctx":"Mi animal favorito es el gato."},
{"es":"insecto","en":"insect","pos":"n","emoji":"🦗","ctx":"Hay muchos insectos en el jardín."},
{"es":"madre","en":"mother","pos":"n","emoji":"👩","ctx":"Mi madre cocina muy bien."},
{"es":"padre","en":"father","pos":"n","emoji":"👨","ctx":"Mi padre trabaja mucho."},
{"es":"hermano","en":"brother","pos":"n","emoji":"👦","ctx":"Mi hermano es mayor que yo."},
{"es":"hermana","en":"sister","pos":"n","emoji":"👧","ctx":"Mi hermana vive en Madrid."},
{"es":"hijo","en":"son","pos":"n","emoji":"👦","ctx":"Mi hijo tiene diez años."},
{"es":"hija","en":"daughter","pos":"n","emoji":"👧","ctx":"Mi hija es muy lista."},
{"es":"abuelo","en":"grandfather","pos":"n","emoji":"👴","ctx":"Mi abuelo cuenta historias."},
{"es":"abuela","en":"grandmother","pos":"n","emoji":"👵","ctx":"Mi abuela hace el mejor pastel."},
{"es":"tío","en":"uncle","pos":"n","emoji":"👨","ctx":"Mi tío vive en otra ciudad."},
{"es":"tía","en":"aunt","pos":"n","emoji":"👩","ctx":"Mi tía viene a visitarnos."},
{"es":"primo","en":"cousin","pos":"n","emoji":"🧑","ctx":"Mi primo juega conmigo."},
{"es":"prima","en":"cousin","pos":"n","emoji":"👩","ctx":"Mi prima es muy divertida."},
{"es":"amigo","en":"friend","pos":"n","emoji":"🤝","ctx":"Mi amigo vive cerca de aquí."},
{"es":"amiga","en":"friend","pos":"n","emoji":"👭","ctx":"Mi amiga y yo vamos al cine."},
{"es":"bebé","en":"baby","pos":"n","emoji":"👶","ctx":"El bebé duerme mucho."},
{"es":"niño","en":"boy","pos":"n","emoji":"👦","ctx":"El niño juega en el parque."},
{"es":"niña","en":"girl","pos":"n","emoji":"👧","ctx":"La niña lee un libro."},
{"es":"hombre","en":"man","pos":"n","emoji":"👨","ctx":"El hombre camina por la calle."},
{"es":"mujer","en":"woman","pos":"n","emoji":"👩","ctx":"La mujer habla por teléfono."},
{"es":"persona","en":"person","pos":"n","emoji":"🧑","ctx":"Esa persona es muy amable."},
{"es":"vecino","en":"neighbor","pos":"n","emoji":"🏘️","ctx":"Mi vecino es muy simpático."},
{"es":"novio","en":"boyfriend","pos":"n","emoji":"💑","ctx":"Mi novio es muy cariñoso."},
{"es":"novia","en":"girlfriend","pos":"n","emoji":"💑","ctx":"Mi novia vive en Barcelona."},
{"es":"esposo","en":"husband","pos":"n","emoji":"💍","ctx":"Mi esposo trabaja en el hospital."},
{"es":"esposa","en":"wife","pos":"n","emoji":"💍","ctx":"Mi esposa es doctora."},
{"es":"familia","en":"family","pos":"n","emoji":"👨‍👩‍👧‍👦","ctx":"Mi familia es muy grande."},
{"es":"papá","en":"dad","pos":"n","emoji":"👨","ctx":"Mi papá me lleva al colegio."},
{"es":"mamá","en":"mom","pos":"n","emoji":"👩","ctx":"Mi mamá me quiere mucho."},
{"es":"sobrino","en":"nephew","pos":"n","emoji":"👦","ctx":"Mi sobrino tiene cinco años."},
{"es":"sobrina","en":"niece","pos":"n","emoji":"👧","ctx":"Mi sobrina es muy inteligente."},
{"es":"nieto","en":"grandson","pos":"n","emoji":"👦","ctx":"Mi nieto viene los domingos."},
{"es":"nieta","en":"granddaughter","pos":"n","emoji":"👧","ctx":"Mi nieta tiene tres años."},
{"es":"maestro","en":"teacher","pos":"n","emoji":"👨‍🏫","ctx":"El maestro explica la lección."},
{"es":"doctor","en":"doctor","pos":"n","emoji":"👨‍⚕️","ctx":"El doctor me revisa la salud."},
{"es":"estudiante","en":"student","pos":"n","emoji":"🎓","ctx":"El estudiante estudia mucho."},
{"es":"jefe","en":"boss","pos":"n","emoji":"💼","ctx":"Mi jefe es muy bueno."},
{"es":"rey","en":"king","pos":"n","emoji":"👑","ctx":"El rey vive en el castillo."},
{"es":"reina","en":"queen","pos":"n","emoji":"👸","ctx":"La reina lleva una corona."},
{"es":"príncipe","en":"prince","pos":"n","emoji":"🤴","ctx":"El príncipe es joven y valiente."},
{"es":"princesa","en":"princess","pos":"n","emoji":"👸","ctx":"La princesa vive en el palacio."},
{"es":"señor","en":"mister","pos":"n","emoji":"🧑","ctx":"Buenos días, señor García."},
{"es":"señora","en":"mrs.","pos":"n","emoji":"👩","ctx":"La señora López es nuestra vecina."},
{"es":"chico","en":"boy","pos":"n","emoji":"👦","ctx":"El chico es muy alto."},
{"es":"chica","en":"girl","pos":"n","emoji":"👩","ctx":"La chica tiene el pelo largo."},
{"es":"gente","en":"people","pos":"n","emoji":"👥","ctx":"Hay mucha gente en la calle."},
{"es":"compañero","en":"classmate","pos":"n","emoji":"🧑‍🤝‍🧑","ctx":"Mi compañero de clase es simpático."},
{"es":"pareja","en":"partner","pos":"n","emoji":"💑","ctx":"Mi pareja y yo viajamos juntos."},
{"es":"nombre","en":"name","pos":"n","emoji":"📛","ctx":"¿Cuál es tu nombre?"},
{"es":"cabeza","en":"head","pos":"n","emoji":"🗣️","ctx":"Me duele la cabeza."},
{"es":"cara","en":"face","pos":"n","emoji":"😊","ctx":"Tiene una cara bonita."},
{"es":"ojo","en":"eye","pos":"n","emoji":"👁️","ctx":"Tiene los ojos verdes."},
{"es":"nariz","en":"nose","pos":"n","emoji":"👃","ctx":"Tiene la nariz pequeña."},
{"es":"boca","en":"mouth","pos":"n","emoji":"👄","ctx":"Abre la boca, por favor."},
{"es":"oreja","en":"ear","pos":"n","emoji":"👂","ctx":"Me duele la oreja."},
{"es":"pelo","en":"hair","pos":"n","emoji":"💇","ctx":"Tiene el pelo largo y oscuro."},
{"es":"mano","en":"hand","pos":"n","emoji":"✋","ctx":"Dame la mano."},
{"es":"dedo","en":"finger","pos":"n","emoji":"👆","ctx":"Me corté el dedo."},
{"es":"brazo","en":"arm","pos":"n","emoji":"💪","ctx":"Levanta el brazo derecho."},
{"es":"pierna","en":"leg","pos":"n","emoji":"🦵","ctx":"Me duele la pierna."},
{"es":"pie","en":"foot","pos":"n","emoji":"🦶","ctx":"Tengo los pies cansados."},
{"es":"espalda","en":"back","pos":"n","emoji":"🔙","ctx":"Me duele la espalda."},
{"es":"cuello","en":"neck","pos":"n","emoji":"🧣","ctx":"Tengo dolor en el cuello."},
{"es":"hombro","en":"shoulder","pos":"n","emoji":"🤷","ctx":"Me duele el hombro izquierdo."},
{"es":"rodilla","en":"knee","pos":"n","emoji":"🦵","ctx":"Me lastimé la rodilla."},
{"es":"diente","en":"tooth","pos":"n","emoji":"🦷","ctx":"Me duele un diente."},
{"es":"lengua","en":"tongue","pos":"n","emoji":"👅","ctx":"La lengua sirve para probar la comida."},
{"es":"corazón","en":"heart","pos":"n","emoji":"❤️","ctx":"Mi corazón late rápido."},
{"es":"pecho","en":"chest","pos":"n","emoji":"🫁","ctx":"Respira con el pecho abierto."},
{"es":"estómago","en":"stomach","pos":"n","emoji":"🤢","ctx":"Me duele el estómago."},
{"es":"sangre","en":"blood","pos":"n","emoji":"🩸","ctx":"La sangre es roja."},
{"es":"hueso","en":"bone","pos":"n","emoji":"🦴","ctx":"El perro come un hueso."},
{"es":"piel","en":"skin","pos":"n","emoji":"🧴","ctx":"Tiene la piel muy suave."},
{"es":"cuerpo","en":"body","pos":"n","emoji":"🧍","ctx":"El cuerpo necesita descanso."},
{"es":"labio","en":"lip","pos":"n","emoji":"👄","ctx":"Tiene los labios rojos."},
{"es":"ceja","en":"eyebrow","pos":"n","emoji":"🤨","ctx":"Levanta una ceja."},
{"es":"frente","en":"forehead","pos":"n","emoji":"😶","ctx":"Tiene la frente ancha."},
{"es":"mejilla","en":"cheek","pos":"n","emoji":"😊","ctx":"Le dio un beso en la mejilla."},
{"es":"barbilla","en":"chin","pos":"n","emoji":"😐","ctx":"Se toca la barbilla cuando piensa."},
{"es":"muñeca","en":"wrist","pos":"n","emoji":"⌚","ctx":"Lleva un reloj en la muñeca."},
{"es":"tobillo","en":"ankle","pos":"n","emoji":"🦶","ctx":"Me torcí el tobillo."},
{"es":"uña","en":"nail","pos":"n","emoji":"💅","ctx":"Se pinta las uñas de rojo."},
{"es":"músculo","en":"muscle","pos":"n","emoji":"💪","ctx":"El músculo está fuerte."},
{"es":"cerebro","en":"brain","pos":"n","emoji":"🧠","ctx":"El cerebro es muy importante."},
{"es":"pulmón","en":"lung","pos":"n","emoji":"🫁","ctx":"Los pulmones necesitan aire limpio."},
{"es":"camisa","en":"shirt","pos":"n","emoji":"👔","ctx":"La camisa es blanca."},
{"es":"pantalón","en":"pants","pos":"n","emoji":"👖","ctx":"El pantalón es azul."},
{"es":"zapato","en":"shoe","pos":"n","emoji":"👞","ctx":"Necesito zapatos nuevos."},
{"es":"vestido","en":"dress","pos":"n","emoji":"👗","ctx":"El vestido rojo es bonito."},
{"es":"falda","en":"skirt","pos":"n","emoji":"👗","ctx":"La falda es muy corta."},
{"es":"chaqueta","en":"jacket","pos":"n","emoji":"🧥","ctx":"Ponte la chaqueta, hace frío."},
{"es":"abrigo","en":"coat","pos":"n","emoji":"🧥","ctx":"El abrigo es muy caliente."},
{"es":"sombrero","en":"hat","pos":"n","emoji":"🎩","ctx":"Lleva un sombrero grande."},
{"es":"gorra","en":"cap","pos":"n","emoji":"🧢","ctx":"La gorra me protege del sol."},
{"es":"calcetín","en":"sock","pos":"n","emoji":"🧦","ctx":"Los calcetines son de algodón."},
{"es":"guante","en":"glove","pos":"n","emoji":"🧤","ctx":"Los guantes me protegen del frío."},
{"es":"bufanda","en":"scarf","pos":"n","emoji":"🧣","ctx":"La bufanda es de lana."},
{"es":"bolso","en":"purse","pos":"n","emoji":"👜","ctx":"Deja el bolso en la mesa."},
{"es":"cinturón","en":"belt","pos":"n","emoji":"🪢","ctx":"Necesito un cinturón negro."},
{"es":"corbata","en":"tie","pos":"n","emoji":"👔","ctx":"La corbata es elegante."},
{"es":"camiseta","en":"t-shirt","pos":"n","emoji":"👕","ctx":"La camiseta es de algodón."},
{"es":"ropa","en":"clothes","pos":"n","emoji":"👚","ctx":"Necesito lavar la ropa."},
{"es":"bota","en":"boot","pos":"n","emoji":"👢","ctx":"Las botas son para la lluvia."},
{"es":"traje","en":"suit","pos":"n","emoji":"🤵","ctx":"Lleva un traje elegante."},
{"es":"pijama","en":"pajamas","pos":"n","emoji":"🩳","ctx":"Me pongo el pijama para dormir."},
{"es":"anillo","en":"ring","pos":"n","emoji":"💍","ctx":"El anillo es de oro."},
{"es":"collar","en":"necklace","pos":"n","emoji":"📿","ctx":"El collar tiene piedras brillantes."},
{"es":"gafas","en":"glasses","pos":"n","emoji":"👓","ctx":"Necesito gafas para leer."},
{"es":"manga","en":"sleeve","pos":"n","emoji":"👔","ctx":"La camisa tiene manga larga."},
{"es":"bolsillo","en":"pocket","pos":"n","emoji":"👖","ctx":"Guarda las llaves en el bolsillo."},
{"es":"sudadera","en":"sweatshirt","pos":"n","emoji":"👕","ctx":"La sudadera es cómoda."},
{"es":"uniforme","en":"uniform","pos":"n","emoji":"🎽","ctx":"Los estudiantes llevan uniforme."},
{"es":"sandalia","en":"sandal","pos":"n","emoji":"🩴","ctx":"Llevo sandalias en verano."},
{"es":"talla","en":"size","pos":"n","emoji":"📏","ctx":"¿Cuál es tu talla?"},
{"es":"casa","en":"house","pos":"n","emoji":"🏠","ctx":"Mi casa tiene un jardín grande."},
{"es":"puerta","en":"door","pos":"n","emoji":"🚪","ctx":"Cierra la puerta, por favor."},
{"es":"ventana","en":"window","pos":"n","emoji":"🪟","ctx":"Abre la ventana."},
{"es":"cocina","en":"kitchen","pos":"n","emoji":"🍳","ctx":"La cocina es grande."},
{"es":"baño","en":"bathroom","pos":"n","emoji":"🚿","ctx":"El baño está limpio."},
{"es":"dormitorio","en":"bedroom","pos":"n","emoji":"🛏️","ctx":"Mi dormitorio es pequeño."},
{"es":"sala","en":"living room","pos":"n","emoji":"🛋️","ctx":"La familia está en la sala."},
{"es":"mesa","en":"table","pos":"n","emoji":"🪑","ctx":"Pon los platos en la mesa."},
{"es":"silla","en":"chair","pos":"n","emoji":"🪑","ctx":"Siéntate en la silla."},
{"es":"cama","en":"bed","pos":"n","emoji":"🛏️","ctx":"La cama es muy cómoda."},
{"es":"sofá","en":"sofa","pos":"n","emoji":"🛋️","ctx":"Descansamos en el sofá."},
{"es":"lámpara","en":"lamp","pos":"n","emoji":"💡","ctx":"Enciende la lámpara."},
{"es":"espejo","en":"mirror","pos":"n","emoji":"🪞","ctx":"Me miro en el espejo."},
{"es":"escalera","en":"stairs","pos":"n","emoji":"🪜","ctx":"Sube por la escalera."},
{"es":"techo","en":"ceiling","pos":"n","emoji":"🏠","ctx":"El techo es muy alto."},
{"es":"suelo","en":"floor","pos":"n","emoji":"🏠","ctx":"El suelo está limpio."},
{"es":"pared","en":"wall","pos":"n","emoji":"🧱","ctx":"La pared es blanca."},
{"es":"jardín","en":"garden","pos":"n","emoji":"🌻","ctx":"Las flores crecen en el jardín."},
{"es":"llave","en":"key","pos":"n","emoji":"🔑","ctx":"No encuentro la llave."},
{"es":"alfombra","en":"carpet","pos":"n","emoji":"🟫","ctx":"La alfombra es suave."},
{"es":"cortina","en":"curtain","pos":"n","emoji":"🪟","ctx":"Las cortinas son de color azul."},
{"es":"almohada","en":"pillow","pos":"n","emoji":"🛏️","ctx":"La almohada es muy suave."},
{"es":"sábana","en":"sheet","pos":"n","emoji":"🛏️","ctx":"Las sábanas están limpias."},
{"es":"manta","en":"blanket","pos":"n","emoji":"🛏️","ctx":"La manta me da calor."},
{"es":"ducha","en":"shower","pos":"n","emoji":"🚿","ctx":"Me baño en la ducha."},
{"es":"garaje","en":"garage","pos":"n","emoji":"🏗️","ctx":"El coche está en el garaje."},
{"es":"balcón","en":"balcony","pos":"n","emoji":"🏠","ctx":"Tomamos café en el balcón."},
{"es":"chimenea","en":"fireplace","pos":"n","emoji":"🔥","ctx":"La chimenea da calor en invierno."},
{"es":"cajón","en":"drawer","pos":"n","emoji":"🗄️","ctx":"Los calcetines están en el cajón."},
{"es":"estante","en":"shelf","pos":"n","emoji":"📚","ctx":"Los libros están en el estante."},
{"es":"armario","en":"closet","pos":"n","emoji":"🚪","ctx":"La ropa está en el armario."},
{"es":"nevera","en":"refrigerator","pos":"n","emoji":"🧊","ctx":"La leche está en la nevera."},
{"es":"horno","en":"oven","pos":"n","emoji":"🔥","ctx":"El pastel está en el horno."},
{"es":"lavadora","en":"washing machine","pos":"n","emoji":"🧺","ctx":"Pongo la ropa en la lavadora."},
{"es":"televisor","en":"television","pos":"n","emoji":"📺","ctx":"El televisor es grande."},
{"es":"habitación","en":"room","pos":"n","emoji":"🏠","ctx":"Mi habitación tiene una ventana."},
{"es":"piso","en":"apartment","pos":"n","emoji":"🏢","ctx":"Vivo en un piso pequeño."},
{"es":"edificio","en":"building","pos":"n","emoji":"🏢","ctx":"El edificio tiene diez pisos."},
{"es":"mueble","en":"furniture","pos":"n","emoji":"🛋️","ctx":"Los muebles son nuevos."},
{"es":"jabón","en":"soap","pos":"n","emoji":"🧼","ctx":"Lávate las manos con jabón."},
{"es":"toalla","en":"towel","pos":"n","emoji":"🛁","ctx":"La toalla está en el baño."},
{"es":"libro","en":"book","pos":"n","emoji":"📖","ctx":"Leo un libro cada semana."},
{"es":"papel","en":"paper","pos":"n","emoji":"📄","ctx":"Necesito un papel para escribir."},
{"es":"lápiz","en":"pencil","pos":"n","emoji":"✏️","ctx":"Escribe con el lápiz."},
{"es":"bolígrafo","en":"pen","pos":"n","emoji":"🖊️","ctx":"¿Me prestas tu bolígrafo?"},
{"es":"teléfono","en":"phone","pos":"n","emoji":"📱","ctx":"Mi teléfono es nuevo."},
{"es":"reloj","en":"watch","pos":"n","emoji":"⌚","ctx":"El reloj marca las tres."},
{"es":"dinero","en":"money","pos":"n","emoji":"💰","ctx":"No tengo mucho dinero."},
{"es":"moneda","en":"coin","pos":"n","emoji":"🪙","ctx":"Encontré una moneda en el suelo."},
{"es":"bolsa","en":"bag","pos":"n","emoji":"🛍️","ctx":"Lleva la bolsa de la compra."},
{"es":"caja","en":"box","pos":"n","emoji":"📦","ctx":"La caja es de cartón."},
{"es":"botella","en":"bottle","pos":"n","emoji":"🍶","ctx":"La botella está llena de agua."},
{"es":"vaso","en":"glass","pos":"n","emoji":"🥛","ctx":"Dame un vaso de agua."},
{"es":"plato","en":"plate","pos":"n","emoji":"🍽️","ctx":"El plato está en la mesa."},
{"es":"cuchara","en":"spoon","pos":"n","emoji":"🥄","ctx":"Necesito una cuchara para la sopa."},
{"es":"tenedor","en":"fork","pos":"n","emoji":"🍴","ctx":"Come con el tenedor."},
{"es":"cuchillo","en":"knife","pos":"n","emoji":"🔪","ctx":"Corta el pan con el cuchillo."},
{"es":"tijeras","en":"scissors","pos":"n","emoji":"✂️","ctx":"Corta el papel con las tijeras."},
{"es":"computadora","en":"computer","pos":"n","emoji":"💻","ctx":"Trabajo con la computadora."},
{"es":"foto","en":"photo","pos":"n","emoji":"📷","ctx":"Tomamos una foto juntos."},
{"es":"carta","en":"letter","pos":"n","emoji":"✉️","ctx":"Escribo una carta a mi abuela."},
{"es":"regalo","en":"gift","pos":"n","emoji":"🎁","ctx":"Le di un regalo a mi amigo."},
{"es":"juguete","en":"toy","pos":"n","emoji":"🧸","ctx":"El niño juega con su juguete."},
{"es":"paraguas","en":"umbrella","pos":"n","emoji":"☂️","ctx":"Lleva el paraguas porque llueve."},
{"es":"mapa","en":"map","pos":"n","emoji":"🗺️","ctx":"Mira el mapa para encontrar la calle."},
{"es":"bandera","en":"flag","pos":"n","emoji":"🏳️","ctx":"La bandera tiene tres colores."},
{"es":"periódico","en":"newspaper","pos":"n","emoji":"📰","ctx":"Mi papá lee el periódico."},
{"es":"revista","en":"magazine","pos":"n","emoji":"📰","ctx":"Compré una revista nueva."},
{"es":"maleta","en":"suitcase","pos":"n","emoji":"🧳","ctx":"La maleta está lista para el viaje."},
{"es":"vela","en":"candle","pos":"n","emoji":"🕯️","ctx":"Enciende la vela."},
{"es":"cuerda","en":"rope","pos":"n","emoji":"🪢","ctx":"Ata la caja con la cuerda."},
{"es":"máquina","en":"machine","pos":"n","emoji":"⚙️","ctx":"La máquina funciona bien."},
{"es":"rueda","en":"wheel","pos":"n","emoji":"🛞","ctx":"La rueda del coche está rota."},
{"es":"herramienta","en":"tool","pos":"n","emoji":"🔨","ctx":"Necesito una herramienta para arreglar la puerta."},
{"es":"escoba","en":"broom","pos":"n","emoji":"🧹","ctx":"Barre el suelo con la escoba."},
{"es":"basura","en":"trash","pos":"n","emoji":"🗑️","ctx":"Saca la basura, por favor."},
{"es":"globo","en":"balloon","pos":"n","emoji":"🎈","ctx":"El niño tiene un globo rojo."},
{"es":"ser","en":"to be","pos":"v","emoji":"✨","ctx":"Quiero ser doctor."},
{"es":"estar","en":"to be","pos":"v","emoji":"📍","ctx":"Voy a estar en casa hoy."},
{"es":"tener","en":"to have","pos":"v","emoji":"🤲","ctx":"Voy a tener un examen mañana."},
{"es":"hacer","en":"to do","pos":"v","emoji":"🛠️","ctx":"Tengo que hacer la tarea."},
{"es":"ir","en":"to go","pos":"v","emoji":"🚶","ctx":"Quiero ir al parque."},
{"es":"venir","en":"to come","pos":"v","emoji":"🔜","ctx":"¿Puedes venir a mi casa?"},
{"es":"dar","en":"to give","pos":"v","emoji":"🎁","ctx":"Te voy a dar un regalo."},
{"es":"decir","en":"to say","pos":"v","emoji":"💬","ctx":"¿Qué quieres decir?"},
{"es":"poder","en":"to be able to","pos":"v","emoji":"💪","ctx":"No puedo ir mañana."},
{"es":"querer","en":"to want","pos":"v","emoji":"❤️","ctx":"Quiero comer pizza."},
{"es":"saber","en":"to know","pos":"v","emoji":"🧠","ctx":"No sé la respuesta."},
{"es":"comer","en":"to eat","pos":"v","emoji":"🍽️","ctx":"Vamos a comer juntos."},
{"es":"beber","en":"to drink","pos":"v","emoji":"🥤","ctx":"Necesito beber agua."},
{"es":"dormir","en":"to sleep","pos":"v","emoji":"😴","ctx":"Me gusta dormir ocho horas."},
{"es":"hablar","en":"to speak","pos":"v","emoji":"🗣️","ctx":"¿Puedes hablar más despacio?"},
{"es":"escuchar","en":"to listen","pos":"v","emoji":"👂","ctx":"Me gusta escuchar música."},
{"es":"leer","en":"to read","pos":"v","emoji":"📚","ctx":"Me gusta leer libros."},
{"es":"escribir","en":"to write","pos":"v","emoji":"✍️","ctx":"Necesito escribir una carta."},
{"es":"abrir","en":"to open","pos":"v","emoji":"📂","ctx":"Puedes abrir la puerta."},
{"es":"cerrar","en":"to close","pos":"v","emoji":"🚪","ctx":"Voy a cerrar la ventana."},
{"es":"comprar","en":"to buy","pos":"v","emoji":"🛒","ctx":"Quiero comprar frutas."},
{"es":"vender","en":"to sell","pos":"v","emoji":"💲","ctx":"Quiere vender su coche."},
{"es":"trabajar","en":"to work","pos":"v","emoji":"💼","ctx":"Tengo que trabajar mañana."},
{"es":"jugar","en":"to play","pos":"v","emoji":"⚽","ctx":"Los niños van a jugar en el parque."},
{"es":"correr","en":"to run","pos":"v","emoji":"🏃","ctx":"Me gusta correr por la mañana."},
{"es":"caminar","en":"to walk","pos":"v","emoji":"🚶","ctx":"Prefiero caminar al trabajo."},
{"es":"nadar","en":"to swim","pos":"v","emoji":"🏊","ctx":"Sé nadar muy bien."},
{"es":"saltar","en":"to jump","pos":"v","emoji":"🦘","ctx":"Al niño le gusta saltar."},
{"es":"cantar","en":"to sing","pos":"v","emoji":"🎤","ctx":"Me encanta cantar canciones."},
{"es":"bailar","en":"to dance","pos":"v","emoji":"💃","ctx":"Quiero aprender a bailar salsa."},
{"es":"cocinar","en":"to cook","pos":"v","emoji":"👩‍🍳","ctx":"Mi mamá sabe cocinar muy bien."},
{"es":"limpiar","en":"to clean","pos":"v","emoji":"🧹","ctx":"Tengo que limpiar la casa."},
{"es":"lavar","en":"to wash","pos":"v","emoji":"🧼","ctx":"Necesito lavar la ropa."},
{"es":"buscar","en":"to search","pos":"v","emoji":"🔍","ctx":"Voy a buscar mis llaves."},
{"es":"encontrar","en":"to find","pos":"v","emoji":"🔎","ctx":"No puedo encontrar mi teléfono."},
{"es":"llevar","en":"to carry","pos":"v","emoji":"🧳","ctx":"Necesito llevar estas cajas."},
{"es":"poner","en":"to put","pos":"v","emoji":"📥","ctx":"Voy a poner los libros en la mesa."},
{"es":"sacar","en":"to take out","pos":"v","emoji":"📤","ctx":"Voy a sacar la basura."},
{"es":"mirar","en":"to look","pos":"v","emoji":"👀","ctx":"Me gusta mirar las estrellas."},
{"es":"ver","en":"to see","pos":"v","emoji":"👁️","ctx":"¿Puedes ver la montaña?"},
{"es":"pensar","en":"to think","pos":"v","emoji":"🤔","ctx":"Necesito pensar antes de decidir."},
{"es":"sentir","en":"to feel","pos":"v","emoji":"💓","ctx":"Puedo sentir el viento frío."},
{"es":"vivir","en":"to live","pos":"v","emoji":"🏡","ctx":"Quiero vivir en la playa."},
{"es":"morir","en":"to die","pos":"v","emoji":"💀","ctx":"Las flores van a morir sin agua."},
{"es":"pagar","en":"to pay","pos":"v","emoji":"💳","ctx":"Tengo que pagar la cuenta."},
{"es":"esperar","en":"to wait","pos":"v","emoji":"⏳","ctx":"Voy a esperar aquí."},
{"es":"llamar","en":"to call","pos":"v","emoji":"📞","ctx":"Voy a llamar a mi mamá."},
{"es":"entrar","en":"to enter","pos":"v","emoji":"🚪","ctx":"Puedes entrar a la casa."},
{"es":"salir","en":"to leave","pos":"v","emoji":"🚶‍♂️","ctx":"Quiero salir temprano hoy."},
{"es":"llegar","en":"to arrive","pos":"v","emoji":"📍","ctx":"¿A qué hora vas a llegar?"},
{"es":"pasar","en":"to pass","pos":"v","emoji":"➡️","ctx":"El tiempo va a pasar rápido."},
{"es":"conocer","en":"to know","pos":"v","emoji":"🤝","ctx":"Quiero conocer a tu familia."},
{"es":"creer","en":"to believe","pos":"v","emoji":"🙏","ctx":"No puedo creer la noticia."},
{"es":"aprender","en":"to learn","pos":"v","emoji":"📖","ctx":"Quiero aprender español."},
{"es":"enseñar","en":"to teach","pos":"v","emoji":"👨‍🏫","ctx":"Mi profesora sabe enseñar bien."},
{"es":"entender","en":"to understand","pos":"v","emoji":"💡","ctx":"No puedo entender la pregunta."},
{"es":"preguntar","en":"to ask","pos":"v","emoji":"❓","ctx":"Quiero preguntar algo."},
{"es":"responder","en":"to answer","pos":"v","emoji":"💬","ctx":"Necesito responder el mensaje."},
{"es":"ayudar","en":"to help","pos":"v","emoji":"🤝","ctx":"¿Puedes ayudar a tu hermano?"},
{"es":"necesitar","en":"to need","pos":"v","emoji":"🆘","ctx":"Necesito tu ayuda."},
{"es":"gustar","en":"to like","pos":"v","emoji":"👍","ctx":"Me va a gustar la película."},
{"es":"olvidar","en":"to forget","pos":"v","emoji":"🤦","ctx":"No quiero olvidar tu nombre."},
{"es":"recordar","en":"to remember","pos":"v","emoji":"🧠","ctx":"No puedo recordar la dirección."},
{"es":"cambiar","en":"to change","pos":"v","emoji":"🔄","ctx":"Quiero cambiar de ropa."},
{"es":"empezar","en":"to start","pos":"v","emoji":"▶️","ctx":"La clase va a empezar a las nueve."},
{"es":"terminar","en":"to finish","pos":"v","emoji":"🏁","ctx":"Necesito terminar el trabajo."},
{"es":"perder","en":"to lose","pos":"v","emoji":"😢","ctx":"No quiero perder el partido."},
{"es":"ganar","en":"to win","pos":"v","emoji":"🏆","ctx":"Quiero ganar el juego."},
{"es":"tocar","en":"to touch","pos":"v","emoji":"🎸","ctx":"Sé tocar la guitarra."},
{"es":"caer","en":"to fall","pos":"v","emoji":"⬇️","ctx":"Ten cuidado, puedes caer."},
{"es":"subir","en":"to go up","pos":"v","emoji":"⬆️","ctx":"Tengo que subir las escaleras."},
{"es":"bajar","en":"to go down","pos":"v","emoji":"⬇️","ctx":"Voy a bajar al primer piso."},
{"es":"sentar","en":"to sit","pos":"v","emoji":"🪑","ctx":"Me voy a sentar aquí."},
{"es":"levantar","en":"to lift","pos":"v","emoji":"🏋️","ctx":"Necesito levantar la caja."},
{"es":"volver","en":"to return","pos":"v","emoji":"🔙","ctx":"Quiero volver a casa."},
{"es":"dejar","en":"to leave","pos":"v","emoji":"👋","ctx":"Voy a dejar el libro en la mesa."},
{"es":"seguir","en":"to follow","pos":"v","emoji":"➡️","ctx":"Debes seguir caminando."},
{"es":"parecer","en":"to seem","pos":"v","emoji":"🤷","ctx":"Todo va a parecer diferente mañana."},
{"es":"quedar","en":"to stay","pos":"v","emoji":"📍","ctx":"Prefiero quedar en casa."},
{"es":"contar","en":"to count","pos":"v","emoji":"🔢","ctx":"El niño sabe contar hasta diez."},
{"es":"mover","en":"to move","pos":"v","emoji":"🔀","ctx":"Necesito mover esta mesa."},
{"es":"mostrar","en":"to show","pos":"v","emoji":"👉","ctx":"Quiero mostrar mis fotos."},
{"es":"tirar","en":"to throw","pos":"v","emoji":"🤾","ctx":"No debes tirar basura al suelo."},
{"es":"usar","en":"to use","pos":"v","emoji":"🔧","ctx":"Puedes usar mi computadora."},
{"es":"tomar","en":"to take","pos":"v","emoji":"🤲","ctx":"Voy a tomar un café."},
{"es":"recibir","en":"to receive","pos":"v","emoji":"📬","ctx":"Quiero recibir noticias tuyas."},
{"es":"enviar","en":"to send","pos":"v","emoji":"📤","ctx":"Necesito enviar un mensaje."},
{"es":"crear","en":"to create","pos":"v","emoji":"🎨","ctx":"Quiero crear algo nuevo."},
{"es":"romper","en":"to break","pos":"v","emoji":"💔","ctx":"Ten cuidado, puedes romper el vaso."},
{"es":"probar","en":"to try","pos":"v","emoji":"👅","ctx":"Quiero probar la sopa."},
{"es":"elegir","en":"to choose","pos":"v","emoji":"☝️","ctx":"Necesito elegir un color."},
{"es":"gritar","en":"to shout","pos":"v","emoji":"📢","ctx":"No debes gritar en la biblioteca."},
{"es":"llorar","en":"to cry","pos":"v","emoji":"😢","ctx":"El bebé no para de llorar."},
{"es":"reír","en":"to laugh","pos":"v","emoji":"😂","ctx":"Me hace reír mucho."},
{"es":"sonreír","en":"to smile","pos":"v","emoji":"😊","ctx":"Siempre es bueno sonreír."},
{"es":"soñar","en":"to dream","pos":"v","emoji":"💭","ctx":"Me gusta soñar en grande."},
{"es":"conducir","en":"to drive","pos":"v","emoji":"🚗","ctx":"Sé conducir desde los dieciocho años."},
{"es":"viajar","en":"to travel","pos":"v","emoji":"✈️","ctx":"Quiero viajar por el mundo."},
{"es":"descansar","en":"to rest","pos":"v","emoji":"😌","ctx":"Necesito descansar un poco."},
{"es":"dibujar","en":"to draw","pos":"v","emoji":"🎨","ctx":"A mi hija le gusta dibujar."},
{"es":"pintar","en":"to paint","pos":"v","emoji":"🖌️","ctx":"Quiero pintar la pared de azul."},
{"es":"grande","en":"big","pos":"adj","emoji":"🐘","ctx":"La casa es muy grande."},
{"es":"pequeño","en":"small","pos":"adj","emoji":"🐜","ctx":"El ratón es muy pequeño."},
{"es":"bueno","en":"good","pos":"adj","emoji":"👍","ctx":"El libro es muy bueno."},
{"es":"malo","en":"bad","pos":"adj","emoji":"👎","ctx":"El tiempo está muy malo."},
{"es":"nuevo","en":"new","pos":"adj","emoji":"🆕","ctx":"Tengo un coche nuevo."},
{"es":"viejo","en":"old","pos":"adj","emoji":"👴","ctx":"El edificio es muy viejo."},
{"es":"largo","en":"long","pos":"adj","emoji":"📏","ctx":"El camino es muy largo."},
{"es":"corto","en":"short","pos":"adj","emoji":"📐","ctx":"La película es muy corta."},
{"es":"alto","en":"tall","pos":"adj","emoji":"🦒","ctx":"Mi hermano es muy alto."},
{"es":"bajo","en":"short","pos":"adj","emoji":"📉","ctx":"La mesa es muy baja."},
{"es":"gordo","en":"fat","pos":"adj","emoji":"🐷","ctx":"El gato está un poco gordo."},
{"es":"delgado","en":"thin","pos":"adj","emoji":"🧍","ctx":"El chico es alto y delgado."},
{"es":"bonito","en":"pretty","pos":"adj","emoji":"🌸","ctx":"El jardín es muy bonito."},
{"es":"feo","en":"ugly","pos":"adj","emoji":"😖","ctx":"El dibujo no es feo."},
{"es":"fácil","en":"easy","pos":"adj","emoji":"✅","ctx":"El examen es fácil."},
{"es":"difícil","en":"difficult","pos":"adj","emoji":"😰","ctx":"La pregunta es muy difícil."},
{"es":"rápido","en":"fast","pos":"adj","emoji":"🏎️","ctx":"El coche es muy rápido."},
{"es":"lento","en":"slow","pos":"adj","emoji":"🐢","ctx":"El tren es muy lento."},
{"es":"caliente","en":"hot","pos":"adj","emoji":"🔥","ctx":"La sopa está caliente."},
{"es":"frío","en":"cold","pos":"adj","emoji":"🥶","ctx":"El agua está muy fría."},
{"es":"limpio","en":"clean","pos":"adj","emoji":"✨","ctx":"La cocina está limpia."},
{"es":"sucio","en":"dirty","pos":"adj","emoji":"🤢","ctx":"Los zapatos están sucios."},
{"es":"lleno","en":"full","pos":"adj","emoji":"🫙","ctx":"El vaso está lleno."},
{"es":"vacío","en":"empty","pos":"adj","emoji":"📭","ctx":"La caja está vacía."},
{"es":"rico","en":"rich","pos":"adj","emoji":"💰","ctx":"El hombre es muy rico."},
{"es":"pobre","en":"poor","pos":"adj","emoji":"😢","ctx":"La familia es pobre pero feliz."},
{"es":"joven","en":"young","pos":"adj","emoji":"👶","ctx":"La profesora es muy joven."},
{"es":"fuerte","en":"strong","pos":"adj","emoji":"💪","ctx":"El café está muy fuerte."},
{"es":"débil","en":"weak","pos":"adj","emoji":"😷","ctx":"Me siento un poco débil."},
{"es":"contento","en":"happy","pos":"adj","emoji":"😃","ctx":"Estoy muy contento hoy."},
{"es":"triste","en":"sad","pos":"adj","emoji":"😢","ctx":"La película es muy triste."},
{"es":"cansado","en":"tired","pos":"adj","emoji":"😫","ctx":"Estoy muy cansado hoy."},
{"es":"enfermo","en":"sick","pos":"adj","emoji":"🤒","ctx":"Mi hijo está enfermo."},
{"es":"listo","en":"ready","pos":"adj","emoji":"✅","ctx":"¿Estás listo para salir?"},
{"es":"seguro","en":"safe","pos":"adj","emoji":"🔒","ctx":"Este lugar es muy seguro."},
{"es":"libre","en":"free","pos":"adj","emoji":"🕊️","ctx":"El pájaro es libre."},
{"es":"importante","en":"important","pos":"adj","emoji":"⭐","ctx":"Es un día muy importante."},
{"es":"posible","en":"possible","pos":"adj","emoji":"🤞","ctx":"Todo es posible."},
{"es":"necesario","en":"necessary","pos":"adj","emoji":"❗","ctx":"Es necesario estudiar más."},
{"es":"diferente","en":"different","pos":"adj","emoji":"🔄","ctx":"Cada persona es diferente."},
{"es":"mismo","en":"same","pos":"adj","emoji":"🟰","ctx":"Tenemos el mismo libro."},
{"es":"favorito","en":"favorite","pos":"adj","emoji":"⭐","ctx":"Mi color favorito es el azul."},
{"es":"perfecto","en":"perfect","pos":"adj","emoji":"💯","ctx":"El día es perfecto."},
{"es":"terrible","en":"terrible","pos":"adj","emoji":"😱","ctx":"El accidente fue terrible."},
{"es":"barato","en":"cheap","pos":"adj","emoji":"💲","ctx":"Este vestido es muy barato."},
{"es":"caro","en":"expensive","pos":"adj","emoji":"💸","ctx":"El restaurante es muy caro."},
{"es":"dulce","en":"sweet","pos":"adj","emoji":"🍬","ctx":"El pastel es muy dulce."},
{"es":"amargo","en":"bitter","pos":"adj","emoji":"😝","ctx":"El café está amargo."},
{"es":"abierto","en":"open","pos":"adj","emoji":"🔓","ctx":"La tienda está abierta."},
{"es":"cerrado","en":"closed","pos":"adj","emoji":"🔒","ctx":"El museo está cerrado hoy."},
{"es":"tranquilo","en":"calm","pos":"adj","emoji":"😌","ctx":"El pueblo es muy tranquilo."},
{"es":"feliz","en":"happy","pos":"adj","emoji":"😄","ctx":"Soy muy feliz aquí."},
{"es":"uno","en":"one","pos":"n","emoji":"1️⃣","ctx":"Solo tengo uno."},
{"es":"dos","en":"two","pos":"n","emoji":"2️⃣","ctx":"Tengo dos hermanos."},
{"es":"tres","en":"three","pos":"n","emoji":"3️⃣","ctx":"Son las tres de la tarde."},
{"es":"cuatro","en":"four","pos":"n","emoji":"4️⃣","ctx":"Hay cuatro sillas en la mesa."},
{"es":"cinco","en":"five","pos":"n","emoji":"5️⃣","ctx":"Tengo cinco dedos en cada mano."},
{"es":"diez","en":"ten","pos":"n","emoji":"🔟","ctx":"Cuento hasta diez."},
{"es":"cien","en":"one hundred","pos":"n","emoji":"💯","ctx":"Hay cien personas aquí."},
{"es":"rojo","en":"red","pos":"adj","emoji":"🔴","ctx":"La manzana es roja."},
{"es":"azul","en":"blue","pos":"adj","emoji":"🔵","ctx":"El cielo es azul."},
{"es":"verde","en":"green","pos":"adj","emoji":"🟢","ctx":"La hierba es verde."},
{"es":"amarillo","en":"yellow","pos":"adj","emoji":"🟡","ctx":"El sol es amarillo."},
{"es":"blanco","en":"white","pos":"adj","emoji":"⚪","ctx":"La nieve es blanca."},
{"es":"negro","en":"black","pos":"adj","emoji":"⚫","ctx":"El gato es negro."},
{"es":"gris","en":"gray","pos":"adj","emoji":"🩶","ctx":"El cielo está gris hoy."},
{"es":"rosa","en":"pink","pos":"adj","emoji":"🩷","ctx":"Las flores son rosas."},
{"es":"morado","en":"purple","pos":"adj","emoji":"🟣","ctx":"La uva es morada."},
{"es":"marrón","en":"brown","pos":"adj","emoji":"🟤","ctx":"El chocolate es marrón."},
{"es":"hora","en":"hour","pos":"n","emoji":"🕐","ctx":"La clase dura una hora."},
{"es":"minuto","en":"minute","pos":"n","emoji":"⏱️","ctx":"Espera un minuto."},
{"es":"segundo","en":"second","pos":"n","emoji":"⏱️","ctx":"Solo toma un segundo."},
{"es":"día","en":"day","pos":"n","emoji":"☀️","ctx":"Hoy es un buen día."},
{"es":"noche","en":"night","pos":"n","emoji":"🌙","ctx":"La noche es tranquila."},
{"es":"mañana","en":"morning","pos":"n","emoji":"🌅","ctx":"Me levanto por la mañana."},
{"es":"tarde","en":"afternoon","pos":"n","emoji":"🌇","ctx":"Estudio por la tarde."},
{"es":"semana","en":"week","pos":"n","emoji":"📅","ctx":"La semana tiene siete días."},
{"es":"mes","en":"month","pos":"n","emoji":"📆","ctx":"Enero es el primer mes del año."},
{"es":"año","en":"year","pos":"n","emoji":"🗓️","ctx":"El año tiene doce meses."},
{"es":"hoy","en":"today","pos":"adv","emoji":"📌","ctx":"Hoy es un día especial."},
{"es":"ayer","en":"yesterday","pos":"adv","emoji":"⏪","ctx":"Ayer fui al cine."},
{"es":"siempre","en":"always","pos":"adv","emoji":"♾️","ctx":"Siempre llego temprano."},
{"es":"nunca","en":"never","pos":"adv","emoji":"🚫","ctx":"Nunca como chocolate."},
{"es":"ahora","en":"now","pos":"adv","emoji":"⏰","ctx":"Tengo que irme ahora."},
{"es":"después","en":"after","pos":"adv","emoji":"➡️","ctx":"Hablamos después."},
{"es":"antes","en":"before","pos":"adv","emoji":"⬅️","ctx":"Llega antes de las ocho."},
{"es":"temprano","en":"early","pos":"adv","emoji":"🌅","ctx":"Me levanto temprano."},
{"es":"aquí","en":"here","pos":"adv","emoji":"📍","ctx":"Ven aquí, por favor."},
{"es":"allí","en":"there","pos":"adv","emoji":"👉","ctx":"Mi casa está allí."},
{"es":"muy","en":"very","pos":"adv","emoji":"❗","ctx":"La comida está muy buena."},
{"es":"también","en":"also","pos":"adv","emoji":"➕","ctx":"Yo también quiero ir."},
{"es":"bien","en":"well","pos":"adv","emoji":"👌","ctx":"Todo está bien."},
{"es":"mal","en":"badly","pos":"adv","emoji":"👎","ctx":"Me siento mal hoy."},
{"es":"mucho","en":"a lot","pos":"adv","emoji":"📈","ctx":"Me gusta mucho esta canción."},
{"es":"poco","en":"a little","pos":"adv","emoji":"🤏","ctx":"Hablo un poco de inglés."},
{"es":"más","en":"more","pos":"adv","emoji":"➕","ctx":"Quiero más agua."},
{"es":"menos","en":"less","pos":"adv","emoji":"➖","ctx":"Necesito menos azúcar."},
{"es":"sí","en":"yes","pos":"adv","emoji":"✅","ctx":"Sí, quiero ir contigo."},
{"es":"no","en":"no","pos":"adv","emoji":"❌","ctx":"No, gracias."},
{"es":"ya","en":"already","pos":"adv","emoji":"✔️","ctx":"Ya terminé mi tarea."},
{"es":"todavía","en":"still","pos":"adv","emoji":"⏳","ctx":"Todavía estoy estudiando."},
{"es":"pronto","en":"soon","pos":"adv","emoji":"🔜","ctx":"Nos vemos pronto."},
{"es":"lejos","en":"far","pos":"adv","emoji":"🔭","ctx":"La escuela está lejos."},
{"es":"cerca","en":"near","pos":"adv","emoji":"📍","ctx":"El parque está cerca de mi casa."},
{"es":"sol","en":"sun","pos":"n","emoji":"☀️","ctx":"El sol sale por la mañana."},
{"es":"luna","en":"moon","pos":"n","emoji":"🌙","ctx":"La luna está llena esta noche."},
{"es":"estrella","en":"star","pos":"n","emoji":"⭐","ctx":"Hay muchas estrellas en el cielo."},
{"es":"nube","en":"cloud","pos":"n","emoji":"☁️","ctx":"Una nube blanca cruza el cielo."},
{"es":"lluvia","en":"rain","pos":"n","emoji":"🌧️","ctx":"La lluvia no para hoy."},
{"es":"nieve","en":"snow","pos":"n","emoji":"❄️","ctx":"La nieve cubre las montañas."},
{"es":"viento","en":"wind","pos":"n","emoji":"💨","ctx":"El viento sopla muy fuerte."},
{"es":"cielo","en":"sky","pos":"n","emoji":"🌤️","ctx":"El cielo está azul y despejado."},
{"es":"mar","en":"sea","pos":"n","emoji":"🌊","ctx":"El mar está tranquilo hoy."},
{"es":"río","en":"river","pos":"n","emoji":"🏞️","ctx":"El río pasa por el pueblo."},
{"es":"lago","en":"lake","pos":"n","emoji":"🏞️","ctx":"Nadamos en el lago en verano."},
{"es":"montaña","en":"mountain","pos":"n","emoji":"🏔️","ctx":"La montaña tiene nieve en la cima."},
{"es":"bosque","en":"forest","pos":"n","emoji":"🌲","ctx":"El bosque está lleno de árboles."},
{"es":"playa","en":"beach","pos":"n","emoji":"🏖️","ctx":"Vamos a la playa este fin de semana."},
{"es":"arena","en":"sand","pos":"n","emoji":"🏝️","ctx":"Los niños juegan en la arena."},
{"es":"piedra","en":"stone","pos":"n","emoji":"🪨","ctx":"Encontré una piedra bonita en el río."},
{"es":"flor","en":"flower","pos":"n","emoji":"🌸","ctx":"Esta flor huele muy bien."},
{"es":"árbol","en":"tree","pos":"n","emoji":"🌳","ctx":"El árbol da sombra en verano."},
{"es":"hoja","en":"leaf","pos":"n","emoji":"🍃","ctx":"La hoja cae del árbol en otoño."},
{"es":"hierba","en":"grass","pos":"n","emoji":"🌿","ctx":"La hierba del jardín está verde."},
{"es":"tierra","en":"earth","pos":"n","emoji":"🌍","ctx":"La tierra está mojada por la lluvia."},
{"es":"campo","en":"field","pos":"n","emoji":"🌾","ctx":"El campo está lleno de flores."},
{"es":"isla","en":"island","pos":"n","emoji":"🏝️","ctx":"La isla tiene playas hermosas."},
{"es":"fuego","en":"fire","pos":"n","emoji":"🔥","ctx":"El fuego calienta la casa."},
{"es":"arcoíris","en":"rainbow","pos":"n","emoji":"🌈","ctx":"Después de la lluvia sale el arcoíris."},
{"es":"tormenta","en":"storm","pos":"n","emoji":"⛈️","ctx":"La tormenta llegó por la noche."},
{"es":"rayo","en":"lightning","pos":"n","emoji":"⚡","ctx":"Un rayo cayó cerca de aquí."},
{"es":"trueno","en":"thunder","pos":"n","emoji":"🌩️","ctx":"El trueno asustó al perro."},
{"es":"niebla","en":"fog","pos":"n","emoji":"🌫️","ctx":"La niebla no deja ver bien."},
{"es":"hielo","en":"ice","pos":"n","emoji":"🧊","ctx":"El hielo cubre el lago en invierno."},
{"es":"ola","en":"wave","pos":"n","emoji":"🌊","ctx":"Las olas del mar son grandes hoy."},
{"es":"cascada","en":"waterfall","pos":"n","emoji":"💧","ctx":"La cascada es muy alta y bonita."},
{"es":"desierto","en":"desert","pos":"n","emoji":"🏜️","ctx":"El desierto es muy caliente de día."},
{"es":"valle","en":"valley","pos":"n","emoji":"🏞️","ctx":"El valle está entre dos montañas."},
{"es":"selva","en":"jungle","pos":"n","emoji":"🌴","ctx":"La selva tiene muchos animales."},
{"es":"costa","en":"coast","pos":"n","emoji":"🏖️","ctx":"Vivimos cerca de la costa."},
{"es":"volcán","en":"volcano","pos":"n","emoji":"🌋","ctx":"El volcán está activo todavía."},
{"es":"semilla","en":"seed","pos":"n","emoji":"🌱","ctx":"Planto una semilla en la tierra."},
{"es":"raíz","en":"root","pos":"n","emoji":"🌱","ctx":"La raíz del árbol es muy larga."},
{"es":"rama","en":"branch","pos":"n","emoji":"🌿","ctx":"El pájaro está en la rama del árbol."},
{"es":"pasto","en":"pasture","pos":"n","emoji":"🌱","ctx":"Las vacas comen en el pasto."},
{"es":"rocío","en":"dew","pos":"n","emoji":"💧","ctx":"El rocío brilla por la mañana."},
{"es":"sombra","en":"shadow","pos":"n","emoji":"👤","ctx":"Me siento en la sombra del árbol."},
{"es":"luz","en":"light","pos":"n","emoji":"💡","ctx":"La luz del sol entra por la ventana."},
{"es":"clima","en":"climate","pos":"n","emoji":"🌡️","ctx":"El clima aquí es muy agradable."},
{"es":"naturaleza","en":"nature","pos":"n","emoji":"🍀","ctx":"Me gusta caminar en la naturaleza."},
{"es":"brisa","en":"breeze","pos":"n","emoji":"🍃","ctx":"Una brisa fresca sopla del mar."},
{"es":"amanecer","en":"sunrise","pos":"n","emoji":"🌅","ctx":"El amanecer es hermoso desde aquí."},
{"es":"atardecer","en":"sunset","pos":"n","emoji":"🌇","ctx":"Vemos el atardecer desde la playa."},
{"es":"escuela","en":"school","pos":"n","emoji":"🏫","ctx":"Los niños van a la escuela."},
{"es":"clase","en":"class","pos":"n","emoji":"📚","ctx":"La clase empieza a las ocho."},
{"es":"profesor","en":"teacher","pos":"n","emoji":"👨‍🏫","ctx":"El profesor explica la lección."},
{"es":"examen","en":"exam","pos":"n","emoji":"📝","ctx":"Tengo un examen mañana."},
{"es":"tarea","en":"homework","pos":"n","emoji":"📓","ctx":"Hago la tarea después de la escuela."},
{"es":"nota","en":"grade","pos":"n","emoji":"💯","ctx":"Saqué una buena nota en el examen."},
{"es":"pizarra","en":"blackboard","pos":"n","emoji":"🖊️","ctx":"El profesor escribe en la pizarra."},
{"es":"cuaderno","en":"notebook","pos":"n","emoji":"📒","ctx":"Escribo en mi cuaderno nuevo."},
{"es":"mochila","en":"backpack","pos":"n","emoji":"🎒","ctx":"Mi mochila es azul y grande."},
{"es":"biblioteca","en":"library","pos":"n","emoji":"📖","ctx":"Estudio en la biblioteca todos los días."},
{"es":"universidad","en":"university","pos":"n","emoji":"🎓","ctx":"Quiero ir a la universidad el próximo año."},
{"es":"idioma","en":"language","pos":"n","emoji":"🗣️","ctx":"El español es un idioma bonito."},
{"es":"pregunta","en":"question","pos":"n","emoji":"❓","ctx":"Tengo una pregunta para ti."},
{"es":"respuesta","en":"answer","pos":"n","emoji":"💬","ctx":"No sé la respuesta correcta."},
{"es":"lección","en":"lesson","pos":"n","emoji":"📖","ctx":"La lección de hoy es fácil."},
{"es":"palabra","en":"word","pos":"n","emoji":"🔤","ctx":"No entiendo esta palabra."},
{"es":"número","en":"number","pos":"n","emoji":"🔢","ctx":"¿Cuál es tu número de teléfono?"},
{"es":"letra","en":"letter","pos":"n","emoji":"🔠","ctx":"La primera letra de mi nombre es A."},
{"es":"frase","en":"sentence","pos":"n","emoji":"📝","ctx":"Escribe una frase con esta palabra."},
{"es":"dibujo","en":"drawing","pos":"n","emoji":"🎨","ctx":"El niño hace un dibujo bonito."},
{"es":"borrador","en":"eraser","pos":"n","emoji":"🧽","ctx":"Necesito un borrador para corregir."},
{"es":"regla","en":"ruler","pos":"n","emoji":"📏","ctx":"Uso la regla para dibujar líneas rectas."},
{"es":"ciencia","en":"science","pos":"n","emoji":"🔬","ctx":"Me gusta la clase de ciencia."},
{"es":"matemáticas","en":"mathematics","pos":"n","emoji":"➗","ctx":"Las matemáticas son mi materia favorita."},
{"es":"página","en":"page","pos":"n","emoji":"📄","ctx":"Abre la página diez del libro."},
{"es":"diccionario","en":"dictionary","pos":"n","emoji":"📕","ctx":"Busco la palabra en el diccionario."},
{"es":"prueba","en":"test","pos":"n","emoji":"✅","ctx":"La prueba de historia es el viernes."},
{"es":"tema","en":"topic","pos":"n","emoji":"📌","ctx":"El tema de hoy es la naturaleza."},
{"es":"curso","en":"course","pos":"n","emoji":"📚","ctx":"Estoy tomando un curso de español."},
{"es":"recreo","en":"recess","pos":"n","emoji":"⏸️","ctx":"Los niños juegan durante el recreo."},
{"es":"horario","en":"schedule","pos":"n","emoji":"🗓️","ctx":"El horario de clases cambia cada semestre."},
{"es":"título","en":"title","pos":"n","emoji":"🏆","ctx":"El título del libro es interesante."},
{"es":"dato","en":"fact","pos":"n","emoji":"📊","ctx":"Ese dato es muy importante."},
{"es":"goma","en":"rubber","pos":"n","emoji":"🧹","ctx":"Dame la goma para borrar esto."},
{"es":"aula","en":"classroom","pos":"n","emoji":"🏫","ctx":"El aula está en el segundo piso."},
{"es":"tiza","en":"chalk","pos":"n","emoji":"🖍️","ctx":"El profesor usa tiza para escribir."},
{"es":"carpeta","en":"folder","pos":"n","emoji":"📁","ctx":"Guardo mis papeles en la carpeta."},
{"es":"coche","en":"car","pos":"n","emoji":"🚗","ctx":"Mi coche es de color rojo."},
{"es":"autobús","en":"bus","pos":"n","emoji":"🚌","ctx":"Tomo el autobús para ir al trabajo."},
{"es":"tren","en":"train","pos":"n","emoji":"🚆","ctx":"El tren llega a las diez."},
{"es":"avión","en":"airplane","pos":"n","emoji":"✈️","ctx":"El avión sale a las tres."},
{"es":"barco","en":"boat","pos":"n","emoji":"🚢","ctx":"El barco cruza el mar."},
{"es":"bicicleta","en":"bicycle","pos":"n","emoji":"🚲","ctx":"Voy en bicicleta a la escuela."},
{"es":"taxi","en":"taxi","pos":"n","emoji":"🚕","ctx":"Llamamos un taxi para ir al aeropuerto."},
{"es":"metro","en":"subway","pos":"n","emoji":"🚇","ctx":"El metro es rápido y barato."},
{"es":"calle","en":"street","pos":"n","emoji":"🛤️","ctx":"La calle está llena de gente."},
{"es":"camino","en":"path","pos":"n","emoji":"🛤️","ctx":"Este camino lleva al pueblo."},
{"es":"carretera","en":"highway","pos":"n","emoji":"🛣️","ctx":"La carretera está en buenas condiciones."},
{"es":"estación","en":"station","pos":"n","emoji":"🚉","ctx":"Esperamos en la estación del tren."},
{"es":"aeropuerto","en":"airport","pos":"n","emoji":"🛫","ctx":"Llegamos al aeropuerto temprano."},
{"es":"gasolina","en":"gasoline","pos":"n","emoji":"⛽","ctx":"Necesito poner gasolina al coche."},
{"es":"moto","en":"motorcycle","pos":"n","emoji":"🏍️","ctx":"Mi hermano tiene una moto nueva."},
{"es":"puente","en":"bridge","pos":"n","emoji":"🌉","ctx":"El puente cruza sobre el río."},
{"es":"semáforo","en":"traffic light","pos":"n","emoji":"🚦","ctx":"El semáforo está en rojo."},
{"es":"acera","en":"sidewalk","pos":"n","emoji":"🚶","ctx":"Camino por la acera con cuidado."},
{"es":"esquina","en":"corner","pos":"n","emoji":"📐","ctx":"La tienda está en la esquina."},
{"es":"cruce","en":"crossing","pos":"n","emoji":"🚸","ctx":"Hay un cruce peligroso en esa calle."},
{"es":"pasajero","en":"passenger","pos":"n","emoji":"🧳","ctx":"El pasajero sube al autobús."},
{"es":"conductor","en":"driver","pos":"n","emoji":"🧑‍✈️","ctx":"El conductor maneja con cuidado."},
{"es":"equipaje","en":"luggage","pos":"n","emoji":"🧳","ctx":"Mi equipaje está en el avión."},
{"es":"billete","en":"ticket","pos":"n","emoji":"🎫","ctx":"Compré un billete de tren."},
{"es":"parada","en":"stop","pos":"n","emoji":"🚏","ctx":"La parada del autobús está cerca."},
{"es":"velocidad","en":"speed","pos":"n","emoji":"💨","ctx":"La velocidad máxima es cien."},
{"es":"tráfico","en":"traffic","pos":"n","emoji":"🚗","ctx":"Hay mucho tráfico por la mañana."},
{"es":"viajero","en":"traveler","pos":"n","emoji":"🧳","ctx":"El viajero llega cansado al hotel."},
{"es":"camión","en":"truck","pos":"n","emoji":"🚛","ctx":"El camión lleva fruta al mercado."},
{"es":"ciudad","en":"city","pos":"n","emoji":"🏙️","ctx":"La ciudad tiene muchos edificios."},
{"es":"pueblo","en":"town","pos":"n","emoji":"🏘️","ctx":"Mi pueblo es pequeño y tranquilo."},
{"es":"tienda","en":"store","pos":"n","emoji":"🏪","ctx":"Compro comida en la tienda."},
{"es":"mercado","en":"market","pos":"n","emoji":"🛒","ctx":"El mercado abre los domingos."},
{"es":"hospital","en":"hospital","pos":"n","emoji":"🏥","ctx":"Mi madre trabaja en el hospital."},
{"es":"iglesia","en":"church","pos":"n","emoji":"⛪","ctx":"La iglesia es muy antigua."},
{"es":"parque","en":"park","pos":"n","emoji":"🌳","ctx":"Los niños juegan en el parque."},
{"es":"museo","en":"museum","pos":"n","emoji":"🏛️","ctx":"Visitamos el museo de arte."},
{"es":"restaurante","en":"restaurant","pos":"n","emoji":"🍽️","ctx":"Cenamos en un restaurante nuevo."},
{"es":"hotel","en":"hotel","pos":"n","emoji":"🏨","ctx":"El hotel está cerca de la playa."},
{"es":"banco","en":"bank","pos":"n","emoji":"🏦","ctx":"Voy al banco a sacar dinero."},
{"es":"oficina","en":"office","pos":"n","emoji":"🏢","ctx":"Trabajo en una oficina grande."},
{"es":"plaza","en":"square","pos":"n","emoji":"⛲","ctx":"Nos vemos en la plaza del pueblo."},
{"es":"teatro","en":"theater","pos":"n","emoji":"🎭","ctx":"Vamos al teatro esta noche."},
{"es":"cine","en":"cinema","pos":"n","emoji":"🎬","ctx":"¿Vamos al cine el sábado?"},
{"es":"farmacia","en":"pharmacy","pos":"n","emoji":"💊","ctx":"Compro medicina en la farmacia."},
{"es":"supermercado","en":"supermarket","pos":"n","emoji":"🛒","ctx":"Hago la compra en el supermercado."},
{"es":"barrio","en":"neighborhood","pos":"n","emoji":"🏘️","ctx":"Vivo en un barrio tranquilo."},
{"es":"correo","en":"post office","pos":"n","emoji":"📮","ctx":"Envío la carta en el correo."},
{"es":"estacionamiento","en":"parking lot","pos":"n","emoji":"🅿️","ctx":"El estacionamiento está lleno."},
{"es":"panadería","en":"bakery","pos":"n","emoji":"🥖","ctx":"Compro pan en la panadería."},
{"es":"carnicería","en":"butcher shop","pos":"n","emoji":"🥩","ctx":"La carnicería abre a las nueve."},
{"es":"peluquería","en":"hair salon","pos":"n","emoji":"💇","ctx":"Voy a la peluquería cada mes."},
{"es":"gasolinera","en":"gas station","pos":"n","emoji":"⛽","ctx":"Para en la gasolinera a cargar."},
{"es":"gimnasio","en":"gym","pos":"n","emoji":"🏋️","ctx":"Voy al gimnasio tres veces por semana."},
{"es":"piscina","en":"swimming pool","pos":"n","emoji":"🏊","ctx":"Los niños nadan en la piscina."},
{"es":"estadio","en":"stadium","pos":"n","emoji":"🏟️","ctx":"El estadio está lleno de gente."},
{"es":"torre","en":"tower","pos":"n","emoji":"🗼","ctx":"La torre es muy alta."},
{"es":"castillo","en":"castle","pos":"n","emoji":"🏰","ctx":"Visitamos un castillo antiguo."},
{"es":"fuente","en":"fountain","pos":"n","emoji":"⛲","ctx":"La fuente de la plaza es bonita."},
{"es":"fábrica","en":"factory","pos":"n","emoji":"🏭","ctx":"La fábrica produce coches."},
{"es":"comisaría","en":"police station","pos":"n","emoji":"🚔","ctx":"La comisaría está en la calle principal."},
{"es":"cementerio","en":"cemetery","pos":"n","emoji":"🪦","ctx":"El cementerio está a las afueras del pueblo."},
{"es":"frontera","en":"border","pos":"n","emoji":"🛃","ctx":"La frontera está a una hora de aquí."},
{"es":"monumento","en":"monument","pos":"n","emoji":"🗽","ctx":"El monumento es muy famoso."},
{"es":"muelle","en":"dock","pos":"n","emoji":"⚓","ctx":"Los barcos están en el muelle."},
{"es":"embajada","en":"embassy","pos":"n","emoji":"🏛️","ctx":"La embajada está en el centro."},
{"es":"zoológico","en":"zoo","pos":"n","emoji":"🦁","ctx":"Los niños visitan el zoológico."},
{"es":"volar","en":"to fly","pos":"v","emoji":"🕊️","ctx":"Los pájaros saben volar muy alto."},
{"es":"parar","en":"to stop","pos":"v","emoji":"🛑","ctx":"El autobús va a parar aquí."},
{"es":"oír","en":"to hear","pos":"v","emoji":"👂","ctx":"Puedo oír la música desde aquí."},
{"es":"oler","en":"to smell","pos":"v","emoji":"👃","ctx":"Puedo oler las flores del jardín."},
{"es":"crecer","en":"to grow","pos":"v","emoji":"🌱","ctx":"Las plantas necesitan agua para crecer."},
{"es":"nacer","en":"to be born","pos":"v","emoji":"👶","ctx":"Mi hijo va a nacer en mayo."},
{"es":"despertar","en":"to wake up","pos":"v","emoji":"⏰","ctx":"Me suelo despertar temprano."},
{"es":"levantarse","en":"to get up","pos":"v","emoji":"🛏️","ctx":"Tengo que levantarse a las seis."},
{"es":"sentarse","en":"to sit down","pos":"v","emoji":"🪑","ctx":"Puedes sentarse aquí."},
{"es":"acostarse","en":"to lie down","pos":"v","emoji":"🛌","ctx":"Me voy a acostarse temprano."},
{"es":"vestirse","en":"to get dressed","pos":"v","emoji":"👔","ctx":"Tengo que vestirse rápido."},
{"es":"pedir","en":"to ask for","pos":"v","emoji":"🙏","ctx":"Voy a pedir un café."},
{"es":"traer","en":"to bring","pos":"v","emoji":"📦","ctx":"¿Puedes traer pan de la tienda?"},
{"es":"llenar","en":"to fill","pos":"v","emoji":"🥛","ctx":"Voy a llenar el vaso de agua."},
{"es":"cortar","en":"to cut","pos":"v","emoji":"✂️","ctx":"Necesito cortar el papel."},
{"es":"preparar","en":"to prepare","pos":"v","emoji":"🍳","ctx":"Voy a preparar la cena."},
{"es":"celebrar","en":"to celebrate","pos":"v","emoji":"🎉","ctx":"Vamos a celebrar su cumpleaños."},
{"es":"explicar","en":"to explain","pos":"v","emoji":"📢","ctx":"¿Puedes explicar eso otra vez?"},
{"es":"intentar","en":"to try","pos":"v","emoji":"💪","ctx":"Voy a intentar hacerlo solo."},
{"es":"mejorar","en":"to improve","pos":"v","emoji":"📈","ctx":"Quiero mejorar mi español."},
{"es":"aceptar","en":"to accept","pos":"v","emoji":"✔️","ctx":"Tengo que aceptar la invitación."},
{"es":"devolver","en":"to return","pos":"v","emoji":"↩️","ctx":"Necesito devolver este libro."},
{"es":"compartir","en":"to share","pos":"v","emoji":"🤝","ctx":"Me gusta compartir mi comida."},
{"es":"decidir","en":"to decide","pos":"v","emoji":"🤔","ctx":"Tengo que decidir qué hacer."},
{"es":"servir","en":"to serve","pos":"v","emoji":"🍽️","ctx":"Voy a servir la comida."},
{"es":"cuidar","en":"to take care of","pos":"v","emoji":"❤️","ctx":"Tienes que cuidar a tu hermano."},
{"es":"imaginar","en":"to imagine","pos":"v","emoji":"💭","ctx":"Me gusta imaginar cosas nuevas."},
{"es":"construir","en":"to build","pos":"v","emoji":"🏗️","ctx":"Van a construir una casa nueva."},
{"es":"reparar","en":"to repair","pos":"v","emoji":"🔧","ctx":"Necesito reparar mi bicicleta."},
{"es":"secar","en":"to dry","pos":"v","emoji":"☀️","ctx":"Hay que secar la ropa al sol."},
{"es":"encender","en":"to turn on","pos":"v","emoji":"💡","ctx":"Voy a encender la luz."},
{"es":"apagar","en":"to turn off","pos":"v","emoji":"🔌","ctx":"Hay que apagar la televisión."},
{"es":"colgar","en":"to hang","pos":"v","emoji":"🧥","ctx":"Voy a colgar el abrigo aquí."},
{"es":"cargar","en":"to charge","pos":"v","emoji":"🔋","ctx":"Necesito cargar mi teléfono."},
{"es":"guardar","en":"to save","pos":"v","emoji":"💾","ctx":"Voy a guardar este documento."},
{"es":"acabar","en":"to finish","pos":"v","emoji":"✅","ctx":"Acabo de acabar mi trabajo."},
{"es":"invitar","en":"to invite","pos":"v","emoji":"💌","ctx":"Quiero invitar a mis amigos."},
{"es":"regalar","en":"to give as a gift","pos":"v","emoji":"🎁","ctx":"Le voy a regalar un libro."},
{"es":"saludar","en":"to greet","pos":"v","emoji":"👋","ctx":"Hay que saludar a los vecinos."},
{"es":"abrazar","en":"to hug","pos":"v","emoji":"🤗","ctx":"Quiero abrazar a mi abuela."},
{"es":"besar","en":"to kiss","pos":"v","emoji":"💋","ctx":"El padre va a besar a su hijo."},
{"es":"mentir","en":"to lie","pos":"v","emoji":"🤥","ctx":"No debes mentir a tus padres."},
{"es":"prometer","en":"to promise","pos":"v","emoji":"🤞","ctx":"Te prometo que voy a llegar a tiempo."},
{"es":"exigir","en":"to demand","pos":"v","emoji":"📣","ctx":"El profesor va a exigir silencio."},
{"es":"agradecer","en":"to thank","pos":"v","emoji":"🙏","ctx":"Quiero agradecer tu ayuda."},
{"es":"suave","en":"soft","pos":"adj","emoji":"🧸","ctx":"Esta tela es muy suave."},
{"es":"duro","en":"hard","pos":"adj","emoji":"🪨","ctx":"El pan está duro."},
{"es":"seco","en":"dry","pos":"adj","emoji":"🏜️","ctx":"El clima es seco en verano."},
{"es":"mojado","en":"wet","pos":"adj","emoji":"💧","ctx":"El suelo está mojado por la lluvia."},
{"es":"oscuro","en":"dark","pos":"adj","emoji":"🌑","ctx":"La habitación está muy oscura."},
{"es":"claro","en":"clear","pos":"adj","emoji":"☀️","ctx":"El agua del río es muy clara."},
{"es":"nervioso","en":"nervous","pos":"adj","emoji":"😰","ctx":"Estoy nervioso por el examen."},
{"es":"sano","en":"healthy","pos":"adj","emoji":"💚","ctx":"Comer fruta te mantiene sano."},
{"es":"enojado","en":"angry","pos":"adj","emoji":"😠","ctx":"Mi padre está enojado conmigo."},
{"es":"peligroso","en":"dangerous","pos":"adj","emoji":"⚠️","ctx":"Nadar aquí es peligroso."},
{"es":"igual","en":"equal","pos":"adj","emoji":"🟰","ctx":"Todos somos iguales."},
{"es":"ocupado","en":"busy","pos":"adj","emoji":"🏃","ctx":"Estoy muy ocupado esta semana."},
{"es":"aburrido","en":"bored","pos":"adj","emoji":"😐","ctx":"Estoy aburrido en casa."},
{"es":"divertido","en":"fun","pos":"adj","emoji":"🎉","ctx":"Este juego es muy divertido."},
{"es":"interesante","en":"interesting","pos":"adj","emoji":"🧐","ctx":"El libro es muy interesante."},
{"es":"simpático","en":"nice","pos":"adj","emoji":"😊","ctx":"Tu hermano es muy simpático."},
{"es":"antipático","en":"unpleasant","pos":"adj","emoji":"😒","ctx":"El vecino nuevo es un poco antipático."},
{"es":"famoso","en":"famous","pos":"adj","emoji":"🌟","ctx":"Ese cantante es muy famoso."},
{"es":"extraño","en":"strange","pos":"adj","emoji":"🤨","ctx":"Hay un ruido extraño en la casa."},
{"es":"horrible","en":"horrible","pos":"adj","emoji":"😱","ctx":"La comida estaba horrible."},
{"es":"maravilloso","en":"wonderful","pos":"adj","emoji":"🤩","ctx":"El viaje fue maravilloso."},
{"es":"pesado","en":"heavy","pos":"adj","emoji":"🏋️","ctx":"La maleta es muy pesada."},
{"es":"ligero","en":"light","pos":"adj","emoji":"🪶","ctx":"Este bolso es muy ligero."},
{"es":"ancho","en":"wide","pos":"adj","emoji":"↔️","ctx":"El río es muy ancho aquí."},
{"es":"estrecho","en":"narrow","pos":"adj","emoji":"↕️","ctx":"La calle es muy estrecha."},
{"es":"profundo","en":"deep","pos":"adj","emoji":"🌊","ctx":"El lago es muy profundo."},
{"es":"solo","en":"alone","pos":"adj","emoji":"🧍","ctx":"Estoy solo en casa."},
{"es":"junto","en":"together","pos":"adj","emoji":"🤝","ctx":"Vamos juntos a la fiesta."},
{"es":"verdadero","en":"true","pos":"adj","emoji":"✅","ctx":"Eso es un amigo verdadero."},
{"es":"falso","en":"false","pos":"adj","emoji":"❌","ctx":"Esa noticia es falsa."},
{"es":"correcto","en":"correct","pos":"adj","emoji":"✔️","ctx":"Tu respuesta es correcta."},
{"es":"trabajo","en":"work","pos":"n","emoji":"💼","ctx":"Voy al trabajo a las ocho."},
{"es":"problema","en":"problem","pos":"n","emoji":"⚠️","ctx":"Tenemos un problema con el coche."},
{"es":"ejemplo","en":"example","pos":"n","emoji":"📋","ctx":"Dame un ejemplo por favor."},
{"es":"parte","en":"part","pos":"n","emoji":"🧩","ctx":"Esta es la mejor parte de la película."},
{"es":"mundo","en":"world","pos":"n","emoji":"🌍","ctx":"Quiero viajar por el mundo."},
{"es":"país","en":"country","pos":"n","emoji":"🏳️","ctx":"España es un país muy bonito."},
{"es":"vida","en":"life","pos":"n","emoji":"🌟","ctx":"La vida es bella."},
{"es":"muerte","en":"death","pos":"n","emoji":"💀","ctx":"La muerte es parte de la vida."},
{"es":"amor","en":"love","pos":"n","emoji":"❤️","ctx":"El amor es lo más importante."},
{"es":"salud","en":"health","pos":"n","emoji":"💚","ctx":"La salud es lo primero."},
{"es":"fiesta","en":"party","pos":"n","emoji":"🎉","ctx":"La fiesta es el sábado."},
{"es":"música","en":"music","pos":"n","emoji":"🎵","ctx":"Me gusta escuchar música."},
{"es":"canción","en":"song","pos":"n","emoji":"🎶","ctx":"Esta canción es mi favorita."},
{"es":"película","en":"movie","pos":"n","emoji":"🎬","ctx":"La película fue muy buena."},
{"es":"juego","en":"game","pos":"n","emoji":"🎮","ctx":"Este juego es muy divertido."},
{"es":"historia","en":"story","pos":"n","emoji":"📖","ctx":"Mi abuelo cuenta historias bonitas."},
{"es":"noticia","en":"news","pos":"n","emoji":"📰","ctx":"Leí una noticia interesante."},
{"es":"viaje","en":"trip","pos":"n","emoji":"🧳","ctx":"El viaje fue muy largo."},
{"es":"idea","en":"idea","pos":"n","emoji":"💡","ctx":"Tengo una idea genial."},
{"es":"grupo","en":"group","pos":"n","emoji":"👥","ctx":"Trabajamos en grupo."},
{"es":"orden","en":"order","pos":"n","emoji":"📋","ctx":"Todo está en orden."},
{"es":"peso","en":"weight","pos":"n","emoji":"⚖️","ctx":"¿Cuál es el peso de esta caja?"},
{"es":"forma","en":"shape","pos":"n","emoji":"🔷","ctx":"La mesa tiene forma redonda."},
{"es":"guerra","en":"war","pos":"n","emoji":"⚔️","ctx":"La guerra es terrible."},
{"es":"paz","en":"peace","pos":"n","emoji":"☮️","ctx":"Todos queremos la paz."},
{"es":"gobierno","en":"government","pos":"n","emoji":"🏛️","ctx":"El gobierno toma decisiones importantes."},
{"es":"ley","en":"law","pos":"n","emoji":"⚖️","ctx":"Hay que respetar la ley."},
{"es":"derecho","en":"right","pos":"n","emoji":"✊","ctx":"Todos tenemos el derecho a estudiar."},
{"es":"precio","en":"price","pos":"n","emoji":"🏷️","ctx":"¿Cuál es el precio de esto?"},
{"es":"mensaje","en":"message","pos":"n","emoji":"💬","ctx":"Te envié un mensaje."},
{"es":"señal","en":"sign","pos":"n","emoji":"🚧","ctx":"La señal dice que no se puede pasar."},
{"es":"error","en":"mistake","pos":"n","emoji":"❌","ctx":"Cometí un error en el examen."},
{"es":"color","en":"color","pos":"n","emoji":"🎨","ctx":"¿Cuál es tu color favorito?"},
{"es":"olor","en":"smell","pos":"n","emoji":"👃","ctx":"Hay un olor rico en la cocina."},
{"es":"sabor","en":"flavor","pos":"n","emoji":"👅","ctx":"El sabor de la sopa es bueno."},
{"es":"ruido","en":"noise","pos":"n","emoji":"🔊","ctx":"Hay mucho ruido en la calle."},
{"es":"silencio","en":"silence","pos":"n","emoji":"🤫","ctx":"El silencio es necesario para estudiar."},
{"es":"dolor","en":"pain","pos":"n","emoji":"😣","ctx":"Tengo un dolor en la espalda."},
{"es":"peligro","en":"danger","pos":"n","emoji":"⚠️","ctx":"Hay peligro de caerse aquí."},
{"es":"fuerza","en":"strength","pos":"n","emoji":"💪","ctx":"Necesitas fuerza para mover eso."},
{"es":"energía","en":"energy","pos":"n","emoji":"⚡","ctx":"No tengo energía hoy."},
{"es":"edad","en":"age","pos":"n","emoji":"🎂","ctx":"¿Cuál es tu edad?"},
{"es":"deporte","en":"sport","pos":"n","emoji":"⚽","ctx":"El fútbol es mi deporte favorito."},
{"es":"equipo","en":"team","pos":"n","emoji":"🏅","ctx":"Nuestro equipo ganó el partido."},
{"es":"dentro","en":"inside","pos":"adv","emoji":"📦","ctx":"El gato está dentro de la caja."},
{"es":"fuera","en":"outside","pos":"adv","emoji":"🌳","ctx":"Los niños juegan fuera."},
{"es":"arriba","en":"up","pos":"adv","emoji":"⬆️","ctx":"Mi cuarto está arriba."},
{"es":"abajo","en":"down","pos":"adv","emoji":"⬇️","ctx":"La cocina está abajo."},
{"es":"sobre","en":"on","pos":"prep","emoji":"⬆️","ctx":"El libro está sobre la mesa."},
{"es":"debajo","en":"underneath","pos":"prep","emoji":"⬇️","ctx":"El gato duerme debajo de la cama."},
{"es":"entre","en":"between","pos":"prep","emoji":"↔️","ctx":"La farmacia está entre el banco y la tienda."},
{"es":"contra","en":"against","pos":"prep","emoji":"🆚","ctx":"El equipo juega contra nosotros."},
{"es":"desde","en":"from","pos":"prep","emoji":"➡️","ctx":"Vivo aquí desde el año pasado."},
{"es":"hasta","en":"until","pos":"prep","emoji":"🏁","ctx":"Trabajo hasta las cinco."},
{"es":"hacia","en":"toward","pos":"prep","emoji":"➡️","ctx":"Camina hacia la puerta."},
{"es":"sin","en":"without","pos":"prep","emoji":"🚫","ctx":"No puedo vivir sin música."},
{"es":"con","en":"with","pos":"prep","emoji":"🤝","ctx":"Voy con mi hermano."},
{"es":"para","en":"for","pos":"prep","emoji":"🎯","ctx":"Este regalo es para ti."},
{"es":"por","en":"for","pos":"prep","emoji":"🔄","ctx":"Gracias por tu ayuda."},
{"es":"según","en":"according to","pos":"prep","emoji":"📰","ctx":"Según el mapa estamos cerca."},
{"es":"apenas","en":"barely","pos":"adv","emoji":"🤏","ctx":"Apenas puedo ver sin mis gafas."},
{"es":"bastante","en":"enough","pos":"adv","emoji":"👌","ctx":"Tengo bastante comida."},
{"es":"quizás","en":"maybe","pos":"adv","emoji":"🤷","ctx":"Quizás llueva mañana."},
{"es":"despacio","en":"slowly","pos":"adv","emoji":"🐢","ctx":"Habla más despacio por favor."},
{"es":"además","en":"furthermore","pos":"adv","emoji":"➕","ctx":"Además tengo que comprar pan."},
{"es":"gracias","en":"thank you","pos":"n","emoji":"🙏","ctx":"Muchas gracias por tu ayuda."},
{"es":"favor","en":"favor","pos":"n","emoji":"🤲","ctx":"¿Me haces un favor?"},
{"es":"cosa","en":"thing","pos":"n","emoji":"📦","ctx":"¿Qué es esa cosa?"},
{"es":"lugar","en":"place","pos":"n","emoji":"📍","ctx":"Este lugar es muy bonito."},
{"es":"tiempo","en":"time","pos":"n","emoji":"⏰","ctx":"No tengo mucho tiempo."},
{"es":"vez","en":"time","pos":"n","emoji":"🔁","ctx":"Es la primera vez que vengo."},
{"es":"manera","en":"way","pos":"n","emoji":"🛤️","ctx":"Hay otra manera de hacerlo."},
{"es":"razón","en":"reason","pos":"n","emoji":"🧠","ctx":"Tienes razón en eso."},
{"es":"verdad","en":"truth","pos":"n","emoji":"✅","ctx":"Dime la verdad por favor."},
{"es":"mentira","en":"lie","pos":"n","emoji":"🤥","ctx":"Eso es una mentira."},
{"es":"suerte","en":"luck","pos":"n","emoji":"🍀","ctx":"¡Buena suerte en el examen!"},
{"es":"miedo","en":"fear","pos":"n","emoji":"😨","ctx":"Tengo miedo de la oscuridad."},
{"es":"hambre","en":"hunger","pos":"n","emoji":"🤤","ctx":"Tengo mucha hambre."},
{"es":"sed","en":"thirst","pos":"n","emoji":"🥤","ctx":"Tengo sed después de correr."},
{"es":"sueño","en":"dream","pos":"n","emoji":"💤","ctx":"Tengo mucho sueño."},
{"es":"prisa","en":"hurry","pos":"n","emoji":"🏃","ctx":"Tengo prisa por llegar."},
{"es":"secreto","en":"secret","pos":"n","emoji":"🤫","ctx":"Te voy a contar un secreto."},
{"es":"broma","en":"joke","pos":"n","emoji":"😄","ctx":"Es solo una broma."},
{"es":"sorpresa","en":"surprise","pos":"n","emoji":"🎊","ctx":"Tengo una sorpresa para ti."},
{"es":"acuerdo","en":"agreement","pos":"n","emoji":"🤝","ctx":"Estoy de acuerdo contigo."},
{"es":"culpa","en":"blame","pos":"n","emoji":"😔","ctx":"No es tu culpa."},
{"es":"permiso","en":"permission","pos":"n","emoji":"✋","ctx":"¿Me das permiso para salir?"},
{"es":"recuerdo","en":"memory","pos":"n","emoji":"💭","ctx":"Tengo un bonito recuerdo de ese día."},
{"es":"deseo","en":"wish","pos":"n","emoji":"⭐","ctx":"Mi deseo es viajar a España."},
{"es":"consejo","en":"advice","pos":"n","emoji":"💡","ctx":"Necesito un consejo tuyo."},
{"es":"esfuerzo","en":"effort","pos":"n","emoji":"💪","ctx":"Con esfuerzo todo es posible."},
{"es":"oportunidad","en":"opportunity","pos":"n","emoji":"🚪","ctx":"Esta es una gran oportunidad."},
{"es":"costumbre","en":"habit","pos":"n","emoji":"🔄","ctx":"Tengo la costumbre de leer antes de dormir."},
{"es":"experiencia","en":"experience","pos":"n","emoji":"📚","ctx":"Fue una experiencia increíble."},
{"es":"resultado","en":"result","pos":"n","emoji":"📊","ctx":"El resultado del examen es bueno."},
{"es":"plan","en":"plan","pos":"n","emoji":"📝","ctx":"¿Cuál es el plan para hoy?"},
{"es":"éxito","en":"success","pos":"n","emoji":"🏆","ctx":"Le deseo mucho éxito."},
{"es":"respeto","en":"respect","pos":"n","emoji":"🙏","ctx":"Hay que mostrar respeto a los demás."},
{"es":"confianza","en":"trust","pos":"n","emoji":"🤝","ctx":"La confianza es muy importante."},
{"es":"amistad","en":"friendship","pos":"n","emoji":"👫","ctx":"La amistad es un regalo."},
{"es":"libertad","en":"freedom","pos":"n","emoji":"🕊️","ctx":"La libertad es un derecho de todos."},
{"es":"paciencia","en":"patience","pos":"n","emoji":"⏳","ctx":"Necesitas tener más paciencia."},
{"es":"alegría","en":"joy","pos":"n","emoji":"😊","ctx":"Siento mucha alegría hoy."},
{"es":"esperanza","en":"hope","pos":"n","emoji":"🌈","ctx":"Nunca pierdas la esperanza."},
{"es":"solución","en":"solution","pos":"n","emoji":"🔑","ctx":"Hay una solución para cada problema."},
{"es":"reunión","en":"meeting","pos":"n","emoji":"👥","ctx":"La reunión es a las tres."},
{"es":"cultura","en":"culture","pos":"n","emoji":"🎭","ctx":"La cultura de este país es rica."},
{"es":"ambiente","en":"environment","pos":"n","emoji":"🌿","ctx":"Cuidar el ambiente es importante."},
{"es":"momento","en":"moment","pos":"n","emoji":"⏱️","ctx":"Espera un momento por favor."},
{"es":"paso","en":"step","pos":"n","emoji":"👣","ctx":"Vamos paso a paso."},
{"es":"sitio","en":"place","pos":"n","emoji":"📌","ctx":"Este es un buen sitio para comer."},
{"es":"tipo","en":"type","pos":"n","emoji":"🔤","ctx":"¿Qué tipo de música te gusta?"},
{"es":"cereza","en":"cherry","pos":"n","emoji":"🍒","ctx":"Las cerezas están muy dulces."},
{"es":"melocotón","en":"peach","pos":"n","emoji":"🍑","ctx":"Este melocotón está muy dulce."},
{"es":"aceituna","en":"olive","pos":"n","emoji":"🫒","ctx":"Me gustan las aceitunas verdes."},
{"es":"salchicha","en":"sausage","pos":"n","emoji":"🌭","ctx":"Comemos salchichas en la barbacoa."},
{"es":"yogur","en":"yogurt","pos":"n","emoji":"🥛","ctx":"Desayuno yogur con fruta."},
{"es":"taza","en":"cup","pos":"n","emoji":"☕","ctx":"Tomo una taza de café."},
{"es":"servilleta","en":"napkin","pos":"n","emoji":"🧻","ctx":"¿Me pasas una servilleta?"},
{"es":"pepino","en":"cucumber","pos":"n","emoji":"🥒","ctx":"El pepino es fresco y crujiente."},
{"es":"espinaca","en":"spinach","pos":"n","emoji":"🥬","ctx":"La espinaca tiene mucho hierro."},
{"es":"champiñón","en":"mushroom","pos":"n","emoji":"🍄","ctx":"Me gustan los champiñones en la pizza."},
{"es":"almendra","en":"almond","pos":"n","emoji":"🌰","ctx":"Me gustan las almendras tostadas."},
{"es":"mermelada","en":"jam","pos":"n","emoji":"🍓","ctx":"La mermelada de fresa es mi favorita."},
{"es":"cereal","en":"cereal","pos":"n","emoji":"🥣","ctx":"Desayuno cereal con leche."},
{"es":"atún","en":"tuna","pos":"n","emoji":"🐟","ctx":"Hago una ensalada de atún."},
{"es":"camarón","en":"shrimp","pos":"n","emoji":"🦐","ctx":"Los camarones están frescos."},
{"es":"bistec","en":"steak","pos":"n","emoji":"🥩","ctx":"Quiero un bistec bien cocido."},
{"es":"tocino","en":"bacon","pos":"n","emoji":"🥓","ctx":"El tocino huele muy bien."},
{"es":"masa","en":"dough","pos":"n","emoji":"🫓","ctx":"La masa para la pizza está lista."},
{"es":"vinagre","en":"vinegar","pos":"n","emoji":"🫙","ctx":"La ensalada lleva aceite y vinagre."},
{"es":"mostaza","en":"mustard","pos":"n","emoji":"🟡","ctx":"¿Quieres mostaza en tu bocadillo?"},
{"es":"mayonesa","en":"mayonnaise","pos":"n","emoji":"🥫","ctx":"No me gusta la mayonesa."},
{"es":"bandeja","en":"tray","pos":"n","emoji":"🍽️","ctx":"Pon los vasos en la bandeja."},
{"es":"olla","en":"pot","pos":"n","emoji":"🍲","ctx":"La sopa se cocina en la olla."},
{"es":"sartén","en":"frying pan","pos":"n","emoji":"🍳","ctx":"Fríe el huevo en la sartén."},
{"es":"cepillo","en":"brush","pos":"n","emoji":"🪥","ctx":"Usa el cepillo para lavarte los dientes."},
{"es":"pasta","en":"paste","pos":"n","emoji":"🦷","ctx":"Necesito pasta de dientes nueva."},
{"es":"peine","en":"comb","pos":"n","emoji":"💇","ctx":"Me peino con el peine todas las mañanas."},
{"es":"esponja","en":"sponge","pos":"n","emoji":"🧽","ctx":"Limpia el plato con la esponja."}
];
